### ISSUE TITLE
App getting crashed on startup

### ISSUE THREAD

**Issue by lp007lp** [Sh1d0w/multi_image_picker#119]
**Bug Report**

`multi_image_picker` version: 4.0.2

Is it happening on Android: Yes

```
 <!-- run `flutter doctor` and paste the output here: -->
PS D:\flutter\projects\xtao> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

• No issues found!
```

**Describe the bug**

I created a flutter project just using the multi_image_picker plugin, and the project has been migrated to the AndroidX repertory. It always crashes when I use phone or emulator to launch the project, and the output information of the terminal stays in the state of installing app, just as shown below:

PS D:\flutter\projects\xtao> flutter run
Launching lib/main.dart on NX529J in debug mode...
Initializing gradle...                                              2.9s
Resolving dependencies...                                           7.7s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         6.4s
Built build\app\outputs\apk\debug\app-debug.apk.
PS D:\flutter\projects\xtao> flutter run
Launching lib/main.dart on NX529J in debug mode...
Initializing gradle...                                              1.2s
Resolving dependencies...                                           6.2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.7s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        27.8s

**Comment by Sh1d0w** [comment]
Can you run `adb logcat` in separate terminal window before you launch the app, you will be able to capture the crash error message with it. Then please provide it here and I will take a look.

**Comment by lp007lp** [comment]
This mistake is the same as the one you solved before. After I migrated the project to the AndroidX library, it still could not run normally in VS Code and in flutter project of Android Studio, and it could only run successfully under the Android model in Android Studio.

logcat message:
`04-12 17:30:38.394 27615-27615/com.example.xtaotest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.xtaotest, PID: 27615
    java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.example.xtaotest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.xtaotest-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5211)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4803)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743)
        at android.app.ActivityThread.access$1500(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:147)
        at android.app.ActivityThread.main(ActivityThread.java:5531)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.example.xtaotest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.xtaotest-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5196)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4803) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:147) 
        at android.app.ActivityThread.main(ActivityThread.java:5531) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.FileProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Comment by Sh1d0w** [comment]
It is trying to load `android.support.v4.content.FileProvider` which is not present anymore in version 4. Can you  please check your AndroidManifest.xml and see if you have defined a file provider? If yes, then remove it.

You can also try `flutter clean` and then try to run the project again.

**Comment by jk199548** [comment]
> It is trying to load `android.support.v4.content.FileProvider` which is not present anymore in version 4. Can you please check your AndroidManifest.xml and see if you have defined a file provider? If yes, then remove it.
> 
> You can also try `flutter clean` and then try to run the project again.

I did what you said. It didn't seem to work.

**Comment by Sh1d0w** [comment]
Please provide example repository where I can reproduce this.

**Comment by jk199548** [comment]
> Please provide example repository where I can reproduce this.

My situation is the same as what lp007lp met. but I did what you said. It didn't seem to work.

**Comment by Sh1d0w** [comment]
@jk199548 The plugin is working ok, you can verify if you run the example app in this repo.

What you experience is because either a misconfiguration on your project or you haven't properly migrated to AndroidX. Without a way to reproduce this I can not help you, because I don't know what you have in your project.

**Comment by lp007lp** [comment]
@Sh1d0w I have solved this problem, maybe I did not successfully migrate the project to AndroidX. I used to manually migrate to AndroidX, now I use automatic migration to AndroidX. Thank you for your help.
