### ISSUE TITLE
我输入选取最大图片数量maxImages为9，当我点击第10张图片的时候，APP强制退出

### ISSUE THREAD

**Issue by 2192555707** [Sh1d0w/multi_image_picker#120]
04-12 17:39:28.253 27200-27200/com.dreamtop.shophelp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dreamtop.shophelp, PID: 27200
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
        at android.view.View.performClick(View.java:4809)
        at android.view.View$PerformClick.run(View.java:20123)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5572)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:966)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/com.dreamtop.shophelp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dreamtop.shophelp-2/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172) 
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71) 
        at android.view.View.performClick(View.java:4809) 
        at android.view.View$PerformClick.run(View.java:20123) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5572) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:966) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761) 
    	Suppressed: java.lang.ClassNotFoundException: com.zhihu.matisse.R$plurals
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by Sh1d0w** [comment]
The latest version of this plugin does not uses Matisse anymore.

If you are using older version, please add the required translations in order to fix this error.

https://github.com/Sh1d0w/multi_image_picker/blob/3.0.22/docs/theming.md
