### ISSUE TITLE
Duplication of requestcode with other plugin causes NPE.

### ISSUE THREAD

**Issue by GwonHyeok** [Sh1d0w/multi_image_picker#127]
**Bug Report**

`multi_image_picker` version: 4.0.1

Is it happening on Android: Yes

Is it happening on iOS: No

```
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale ko-KR)
    • Flutter version 1.4.9-hotfix.1 at /Users/ghyeok/Downloads/flutter
    • Framework revision 88fa7ea403 (7 days ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ghyeok/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/ghyeok/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/ghyeok/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/ghyeok/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • LG F700K • LGF700K6ae46f7e • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Describe the bug**

here is android logcat
```
FATAL EXCEPTION: main
Process: kr.co.rawwave.asktravel, PID: 17567
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { (has extras) }} to activity {kr.co.rawwave.asktravel/kr.co.rawwave.asktravel.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4441)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.d.a.b.onActivityResult(Unknown Source:17)
	at io.flutter.app.FlutterPluginRegistry.onActivityResult(Unknown Source:18)
	at io.flutter.app.FlutterActivityDelegate.onActivityResult(Unknown Source:6)
	at io.flutter.app.FlutterActivity.onActivityResult(Unknown Source:2)
	at android.app.Activity.dispatchActivityResult(Activity.java:7240)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4394)
	... 9 more
```
 
```java
List<Uri> photos = data.getParcelableArrayListExtra(Define.INTENT_PATH);
List<HashMap<String, Object>> result = new ArrayList<>(photos.size());
```

If requescode is duplicated with other plugins, you may encounter a problem where photos is null.

thank you

**Comment by Sh1d0w** [comment]
Thanks for the report, I will look into it.

The problem is that all Flutter plugins register via same listener `PluginRegistry.ActivityResultListener`, which obviously is collision prone. I will research how is best to handle this and will release a fix.

**Comment by Sh1d0w** [comment]
This should be solved in the latest version as the plugin no longer listens for permissions.

**Comment by JosephNK** [comment]
@Sh1d0w 
```
List<Uri> photos = data.getParcelableArrayListExtra(Define.INTENT_PATH);
```
Can't you add the null check logic to that photos variable?
