### ISSUE TITLE
version 2.2.10 won't compile

### ISSUE THREAD

**Issue by Daibaku0615** [Sh1d0w/multi_image_picker#13]
I upgraded to version 2.2.10 but when run the app console says those.
How can I fix this?
Thank you for great plugin!

```
[!] CocoaPods could not find compatible versions for pod "BSImagePicker":
In snapshot (Podfile.lock):
BSImagePicker (= 2.8.0, ~> 2.8)
In Podfile:
multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`) was resolved to 2.1.22, which depends on
BSImagePicker (~> 2.8.2)
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by Sh1d0w** [comment]
Hi, this is because the version of BSImagePicker in your Podfile.lock is outdated. I have updated it in order to support iOS 12 and Swift 4. Please remove the Podfile.lock in your iOS folder and then run the build command again.
