### ISSUE TITLE
my app crashes after calling pickImages

### ISSUE THREAD

**Issue by sasukeamjed** [Sh1d0w/multi_image_picker#145]
please help my app crashes whenever i click on pickImages button, i don't know what is causing this.

here is the error i am getting:

```
E/flutter ( 6294): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/ContextCompat;
E/flutter ( 6294): at com.vitanov.multiimagepicker.MultiImagePickerPlugin.openImagePicker(MultiImagePickerPlugin.java:557)
E/flutter ( 6294): at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:308)
E/flutter ( 6294): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter ( 6294): at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/flutter ( 6294): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/flutter ( 6294): at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 6294): at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 6294): at android.os.Looper.loop(Looper.java:160)
E/flutter ( 6294): at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 6294): at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6294): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 6294): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 6294): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86, /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/base.apk!/lib/x86, /system/lib]]
E/flutter ( 6294): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/flutter ( 6294): at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter ( 6294): at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter ( 6294): ... 12 more
E/flutter ( 6294):
F/flutter ( 6294): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
F/libc ( 6294): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6294 (icker_multi_app), pid 6294 (icker_multi_app)

Build fingerprint: 'google/sdk_gphone_x86/generic_x86:9/PSR1.180720.075/5124027:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 6294, tid: 6294, name: icker_multi_app >>> com.example.image_picker_multi_app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
'
eax 00000000 ebx 00001896 ecx 00001896 edx 00000006
edi 00001896 esi 00000070
ebp fffc2e08 esp fffc2da8 eip ed55eb39
backtrace:
#00 pc 00000b39 [vdso:ed55e000] (__kernel_vsyscall+9)
#1 pc 0001fdf8 /system/lib/libc.so (syscall+40)
#2 pc 00022ed3 /system/lib/libc.so (abort+115)
#3 pc 005e253a /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#4 pc 005d3612 /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#5 pc 005d2356 /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#6 pc 0061d99b /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#7 pc 005e41ff /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#8 pc 005e415e /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#9 pc 005e643e /data/app/com.example.image_picker_multi_app-ZMKZ5SEWjpSDs4Y8SwholA==/lib/x86/libflutter.so (offset 0x59c000)
#10 pc 00012a77 /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39)
#11 pc 00013896 /system/lib/libutils.so (android::Looper::pollInner(int)+998)
#12 pc 0001340b /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+43)
#13 pc 000e414b /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59)
#14 pc 003ddb28 /system/framework/x86/boot-framework.oat (offset 0x3ca000) (android.media.MediaExtractor.seekTo [DEDUPED]+136)
#15 pc 005f0b82 /system/lib/libart.so (art_quick_invoke_stub+338)
#16 pc 000a30ce /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+222)
#17 pc 0029bca2 /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+338)
#18 pc 00293e48 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1048)
#19 pc 005bda66 /system/lib/libart.so (MterpInvokeDirect+342)
#20 pc 005e2e21 /system/lib/libart.so (ExecuteMterpImpl+14497)
#21 pc 00aeae98 /system/framework/boot-framework.vdex (android.os.MessageQueue.next+38)
#22 pc 00266216 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2093054539+598)
#23 pc 0026c79c /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
#24 pc 00293e2b /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1019)
#25 pc 005bc493 /system/lib/libart.so (MterpInvokeVirtual+691)
#26 pc 005e2d21 /system/lib/libart.so (ExecuteMterpImpl+14241)
#27 pc 00aea944 /system/framework/boot-framework.vdex (android.os.Looper.loop+128)
#28 pc 00266216 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2093054539+598)
#29 pc 0026c79c /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
#30 pc 00293e2b /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1019)
#31 pc 005bdc5f /system/lib/libart.so (MterpInvokeStatic+207)
#32 pc 005e2ea1 /system/lib/libart.so (ExecuteMterpImpl+14625)
#33 pc 00384ca2 /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
#34 pc 00266216 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2093054539+598)
#35 pc 0026c68e /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126)
#36 pc 005a953d /system/lib/libart.so (artQuickToInterpreterBridge+1277)
#37 pc 005f6c6d /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
#38 pc 005f0d52 /system/lib/libart.so (art_quick_invoke_static_stub+418)
#39 pc 000a30df /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+239)
#40 pc 004d3349 /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89)
#41 pc 004d502e /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1422)
#42 pc 00449783 /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+83)
#43 pc 0011d778 /system/framework/x86/boot.oat (offset 0x114000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+168)
#44 pc 005f0b82 /system/lib/libart.so (art_quick_invoke_stub+338)
#45 pc 000a30ce /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+222)
#46 pc 0029bca2 /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+338)
#47 pc 00293e48 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1048)
#48 pc 005bc493 /system/lib/libart.so (MterpInvokeVirtual+691)
#49 pc 005e2d21 /system/lib/libart.so (ExecuteMterpImpl+14241)
#50 pc 00c0b7d2 /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
#51 pc 00266216 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2093054539+598)
#52 pc 0026c68e /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126)
#53 pc 005a953d /system/lib/libart.so (artQuickToInterpreterBridge+1277)
#54 pc 005f6c6d /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
#55 pc 00badc3c /system/framework/x86/boot-framework.oat (offset 0x3ca000) (com.android.internal.os.ZygoteInit.main+3100)
#56 pc 005f0d52 /system/lib/libart.so (art_quick_invoke_static_stub+418)
#57 pc 000a30df /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+239)
#58 pc 004d3349 /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89)
#59 pc 004d2fcd /system/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+429)
#60 pc 003a784d /system/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+925)
#61 pc 000d9273 /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+2867)
#62 pc 000c6d29 /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+73)
#63 pc 0007097e /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+62)
#64 pc 00073e78 /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vectorandroid::String8 const&, bool)+744)
#65 pc 00001bb2 /system/bin/app_process32 (main+1506)
#66 pc 000c0f54 /system/lib/libc.so (__libc_init+100)
Application finished.
Failed to send request: {"jsonrpc":"2.0","id":"155","method":"getVM","params":{}}
```

`multi_image_picker` version: ^4.2.0

Is it happening on Android: Yes

Is it happening on iOS: i don't know

```
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code, 64-bit edition (version 1.27.2)
[√] Connected device (1 available)

• No issues found!

```

**Comment by Sh1d0w** [comment]
Have you migrated your project to AndroidX as described in the docs?

**Comment by sasukeamjed** [comment]
Yes I believe i did, not sure if it worked though, is there away to check if the migration was successful or not?!
Sorry for asking stupid questions, i am still beginner in programing

**Comment by Sh1d0w** [comment]
It seems from the error you did not. You can automatically migrate by opening your android project folder with Android Studio and then click Refactor > Migrate to AndroidX from the menu bar.

**Comment by sasukeamjed** [comment]
yes now it is working, thank you mister, i really appreciate your quick support,
again thank you very much,

you can close this now.
