### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by MeriemTazen** [Sh1d0w/multi_image_picker#200]
Hello, i'm trying to use your plugin but it does't work on iOS (didn't try on Android)
i'm using multi_image_picker: ^4.3.5

The error is : 
```
Running pod install...                                              0,8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A multi_image_picker
      - Flutter
      - connectivity
      - flutter_webview_plugin
      - image_picker
      - path_provider
      - shared_preferences
      - sqflite
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "multi_image_picker":
      In Podfile:
        multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)

    Specs satisfying the `multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/resolver.rb:88:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:398:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please
    specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```

Flutter doctor :
```
 [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (1 available)
```

Any idea what is wrong ? Thank !

**Comment by Sh1d0w** [comment]
You need to set platform version in pod file as the error suggests.

https://github.com/Sh1d0w/multi_image_picker/blob/master/example/ios/Podfile#L2

**Comment by MeriemTazen** [comment]
Thank you for your quick answer. After doing this tough, I still have another error

```
Running pod install...                                              2,4s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           23,3s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-07-16 13:22:50.372 xcodebuild[8443:818964]  DTDeviceKit: deviceType from ced76747dccf630b3d00ca6460f7a04ece1f1d19 was
    NULL
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning:
    'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sqlite3.
    h:8245:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as being introduced in iOS 5.0 here, but the deployment target
    is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose
    'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning:
    'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frame
    works/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frame
    works/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch
    /queue.h:1352:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in iOS 5.0 here, but the
    deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose
    'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning:
    'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frame
    works/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frame
    works/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch
    /queue.h:1408:1: note: 'dispatch_get_specific' has been marked as being introduced in iOS 5.0 here, but the deployment
    target is iOS 4.3.0
    dispatch_get_specific(const void *key);
    ^
    /Users/mydomus/Desktop/meriem/flutter/mydomus_edl/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose
    'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/mydomus/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.5/ios/Classes/FlutterWebview
    Plugin.m:263:24: warning: comparison of distinct pointer types ('NSString *' and 'NSNull * _Nonnull')
    [-Wcompare-distinct-pointer-types]
      if (_invalidUrlRegex != [NSNull null] && urlString != nil) {
          ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
    1 warning generated.
    === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/mydomus/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.3.5/ios/Classes/MultiImagePickerPl
    ugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the precompiled application for the device.

```

**Comment by Sh1d0w** [comment]
You need to enable swift support in your project, please read the plugin documentation before opening issues.

**Comment by MeriemTazen** [comment]
Actually it is still not working :(
I added a new Swift File in Xcode, the Bridging Header has been added, I uncommented the " platform :ios, '9.0' ", and SWIFT_VERSION is 5.0 (in Build Settings when I click on the Pods directory). I still have the same error I showed in my previous comment...

**Comment by Sh1d0w** [comment]
@MeriemTazen Can you run `flutter create -i swift .` in your project? Can you also try to run the example app in this repo?

If you can, you can compare the pod file in it with your to see what could be the difference.

**Comment by MeriemTazen** [comment]
when I try **flutter create -i swift, it says :**
Ambiguous organization in existing files: {co.mydomus, com.example}. The --org command line argument must be specified to
recreate project.
I then tried running **flutter create --org co.mydomus -i swift .**, I had the following message

```
Recreating project ....
  ios/Runner/Runner-Bridging-Header.h (created)
  ios/Runner/AppDelegate.swift (created)
  android/app/src/main/java/co/mydomus/mydomus_edl/MainActivity.java (created)
Wrote 5 files.

All done!
[✓] Flutter is fully installed. (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale fr-FR)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS is fully installed. (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices is fully installed.
[✓] Android Studio is fully installed. (version 3.4)
[✓] VS Code is fully installed. (version 1.36.0)
[✓] Connected device is fully installed. (2 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart. 
```

But after running **flutter run** :
```
Running pod install...                                              2,3s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           12,5s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-07-18 10:38:33.103 xcodebuild[28128:1751774]  DTDeviceKit: deviceType from ced76747dccf630b3d00ca6460f7a04ece1f1d19
    was NULL
    2019-07-18 10:38:33.155 xcodebuild[28128:1751837]  DTDeviceKit: deviceType from ced76747dccf630b3d00ca6460f7a04ece1f1d19
    was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/mydomus/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.3.6/ios/Classes/MultiImagePickerPl
    ugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the precompiled application for the device.
```

And when I try to run the example app of this repo, it crashes :
```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 77e2c6eb6e8d5acf)
 
Crash report written to /Users/mydomus/Desktop/testMultiPicker/multi_image_picker/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by Sh1d0w** [comment]
@MeriemTazen hm I am not able to reproduce it.

Can you upgrade to the latest stable flutter version, I see you are on 1.5.4

How do you run the example app in my repo? You need to clone the repo, cd into example folder, execute `flutter packages get` and then `flutter run`.

The error you are getting is because your project was created without Swift support. The command I've sent you is to rebuilt it with Swift support, which is the same as if you created blank swift file through Xcode and followed the prompt afterwards.

Can you provide example repo where I can reproduce the problem, please?

**Comment by MeriemTazen** [comment]
I forgot to run` flutter packages get ` before `flutter run`, but it still crashes after that :/
I upgraded flutter, now I have v1.7.8, but it doesn't change anything to my project or the example in your repo.

I'm going to try a recreate the project and import my files there.

I will also try to provide you an example of my project, a simpler version because I can't show you the whole thing
