### ISSUE TITLE
crashing after upgrading to flutter 1.7.8

### ISSUE THREAD

**Issue by gondaliya** [Sh1d0w/multi_image_picker#203]
**Bug Report**

`multi_image_picker` version: 4.3.6

Is it happening on Android: Yes

Is it happening on iOS: 

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN)
    • Flutter version 1.7.8+hotfix.4 at /home/super/flutter/flutter
    • Framework revision 20e59316b8 (6 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/super/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/77/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (2 available)
    • moto x4                   • ZY224P6XNX    • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

**Describe the bug**

A clear and concise description of what the bug is plugin crashing after upgrading to flutter 1.7.8.

**Comment by dsourav** [comment]
i also have the same problem can any one answer the question

**Comment by Sh1d0w** [comment]
I will take a look tomorrow. It will be very helpful however if you can provide logs of the exact error you are getting.

**Comment by dsourav** [comment]
follow this link it's worked for me  
https://sh1d0w.github.io/multi_image_picker/#/gettingstarted?id=installation

**Comment by Sh1d0w** [comment]
Always read the docs first :)

**Comment by dsourav** [comment]
here is my logcat:
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
E/AndroidRuntime(26417): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.example.design_demo-SKXeJtpnnnwQiDYbue7bRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.design_demo-SKXeJtpnnnwQiDYbue7bRA==/lib/arm64, /data/app/com.example.design_demo-SKXeJtpnnnwQiDYbue7bRA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

i just added the following line into gradle.properties
android.useAndroidX=true
android.enableJetifier=true

**Comment by Sh1d0w** [comment]
This error means that the project was not migrated to Android x as the docs suggest

**Comment by gondaliya** [comment]
my logcat:
2019-07-28 13:51:47.033 1435-1435/com.softellectual.admin_motivation_line E/RecyclerView: No adapter attached; skipping layout
2019-07-28 13:51:47.393 1435-1435/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.softellectual.admin_motivation_line, PID: 1435
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
        at com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(GlideAdapter.java:17)
        at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:56)
        at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:25)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:788)
        at android.view.View.layout(View.java:20680)
        at android.view.ViewGroup.layout(ViewGroup.java:6197)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2830)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2357)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1493)
2019-07-28 13:51:47.395 1435-1435/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7283)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.softellectual.admin_motivation_line-_9UXX9DUyhwdpKQxzIA3Sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.softellectual.admin_motivation_line-_9UXX9DUyhwdpKQxzIA3Sw==/lib/arm64, /data/app/com.softellectual.admin_motivation_line-_9UXX9DUyhwdpKQxzIA3Sw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 63 more

**Comment by Sh1d0w** [comment]
This error is also because your project haven’t been migrated to android x

**Comment by HardikkMadaan** [comment]
I migrated my project to Android x and its not working. I copied the code from the example. And the app crashes as soon as i allow the storage and camera permissions.
