### ISSUE TITLE
crash after permission

### ISSUE THREAD

**Issue by lvshutao** [Sh1d0w/multi_image_picker#229]
**Bug Report**

`multi_image_picker` version: ^4.5.2

Is it happening on Android: Yes

Is it happening on iOS: unknown

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-HK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.37.0)
[✓] Connected device (1 available)
```

after two alter permission (I choice ALLOW), the app crash, and the error info below

```
E/.example.trave( 5647): Invalid ID 0x00000000.
D/AndroidRuntime( 5647): Shutting down VM
E/AndroidRuntime( 5647): FATAL EXCEPTION: main
E/AndroidRuntime( 5647): Process: com.example.travel, PID: 5647
E/AndroidRuntime( 5647): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2001, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.travel/com.example.travel.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime( 5647): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime( 5647): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime( 5647): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 5647): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 5647): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 5647): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime( 5647): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5647): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5647): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 5647): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5647): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 5647): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 5647): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime( 5647): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
E/AndroidRuntime( 5647): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
E/AndroidRuntime( 5647): 	at android.content.res.Resources.getDrawable(Resources.java:827)
E/AndroidRuntime( 5647): 	at android.content.Context.getDrawable(Context.java:626)
E/AndroidRuntime( 5647): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
E/AndroidRuntime( 5647): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:614)
E/AndroidRuntime( 5647): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onRequestPermissionsResult(MultiImagePickerPlugin.java:113)
E/AndroidRuntime( 5647): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime( 5647): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127)
E/AndroidRuntime( 5647): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime( 5647): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
E/AndroidRuntime( 5647): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
E/AndroidRuntime( 5647): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime( 5647): 	... 11 more
I/Process ( 5647): Sending signal. PID: 5647 SIG: 9
Lost connection to device.
```
after I rebuild the app, and try again, the error message is 

```
... long long text ...
E/MethodChannel#multi_image_picker( 7481): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#multi_image_picker( 7481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 7481): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Resource ID #0x0, null)
E/flutter ( 7481): #0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:79:11)
E/flutter ( 7481): <asynchronous suspension>
... 
```

I reinstall the app, the photo permission allow,  camera permission deny, the error message is 

```
E/flutter ( 7773): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Read, write or camera permission was not granted
E/flutter ( 7773): #0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:75:11)
E/flutter ( 7773): <asynchronous suspension>
E/flutter ( 7773): #1      XImagePicker.multiImagePicker (package:easy_frame/src/pkgext/ximage_picker.dart:14:37)
```

**Comment by lvshutao** [comment]
I try in iOS Simulator, and it run successful

**Comment by mattermoran** [comment]
Had the same issue getting android.content.res.Resources$NotFoundException: Resource ID #0x0
After comparing my android folder and the one from example folder I found that it wouldn't work without the back arrow icon in /res folder. To fix it you need to copy these green folders into your /res folder.
![image](https://user-images.githubusercontent.com/29712386/63646723-f2b50380-c749-11e9-8862-bb95ae1047d0.png)

**Comment by mattermoran** [comment]
I see now that I have copied code from example and didn't pay attention that it had backButtonDrawable property set. My bad
![image](https://user-images.githubusercontent.com/29712386/63647140-69a0cb00-c74f-11e9-95bf-9bbb1397bf75.png)

**Comment by Sh1d0w** [comment]
As the others pointed out, you are missing an asset file. Either copy it from the example app where you copied the code or remove it from the config if you aren't going to use one.
