### ISSUE TITLE
Unhandled FormatException while getting MetaData 

### ISSUE THREAD

**Issue by sh0umik** [Sh1d0w/multi_image_picker#274]
**Bug Report**

`multi_image_picker` version: ^4.5.5

Is it happening on Android: Yes

Is it happening on iOS: Not tested

```
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G103, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

This error is happening for some pictures from my gallery but other pictures are fine.

I am calling it like this

```
 Metadata meta = await asset.metadata;
```

E/flutter (23913): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid double
E/flutter (23913): 6432/1000
E/flutter (23913): #0      double.parse (dart:core-patch/double_patch.dart:110:28)
E/flutter (23913): #1      _castAsDouble (package:multi_image_picker/src/metadata.dart:961:43)
E/flutter (23913): #2      new GpsMetadata.fromMap (package:multi_image_picker/src/metadata.dart:843:18)
E/flutter (23913): #3      new Metadata.fromMap (package:multi_image_picker/src/metadata.dart:13:27)
E/flutter (23913): #4      MultiImagePicker.requestMetadata (package:multi_image_picker/src/picker.dart:170:21)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #5      Asset.metadata (package:multi_image_picker/src/asset.dart:137:29)
E/flutter (23913): #6      NativeImagePickerRegistry.multiPickImages.<anonymous closure> (package:restra_mvp/services/native_image_picker.dart:49:35)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #7      Future.forEach.<anonymous closure> (dart:async/future.dart:492:26)
E/flutter (23913): #8      Future.doWhile.<anonymous closure> (dart:async/future.dart:534:26)
E/flutter (23913): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23913): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23913): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23913): #12     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (23913): #13     Future.doWhile (dart:async/future.dart:549:18)
E/flutter (23913): #14     Future.forEach (dart:async/future.dart:490:12)
E/flutter (23913): #15     NativeImagePickerRegistry.multiPickImages (package:restra_mvp/services/native_image_picker.dart:42:18)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #16     PictureBlogBloc.getImage (package:restra_core/src/blocs/input/picture_blog_bloc.dart:33:10)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #17     InputSystem.build.<anonymous closure> (package:restra_mvp/ui/input/input.dart:271:73)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #18     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:655:14)
E/flutter (23913): #19     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:730:32)
E/flutter (23913): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23913): #21     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (23913): #22     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (23913): #23     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (23913): #24     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (23913): #25     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (23913): #26     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (23913): #27     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23913): #28     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23913): #29     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23913): #30     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23913): #31     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (23913): #32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23913): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23913): #34     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (23913): #35     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by Sh1d0w** [comment]
I will fix this. Can you provide the original image with the metadata you are trying with, so I can reproduce the error?

**Comment by sh0umik** [comment]
@Sh1d0w is there any way to only share the picture to you without making it public ?

**Comment by Sh1d0w** [comment]
Yes you can send it to me via email, see the readme file in the repo.

**Comment by Sh1d0w** [comment]
Closing due to inactivity.

**Comment by shetz163** [comment]
my phone is pixel 3xl ,and i got the same error, cuz my photo's exif has a tag 'GPSDOP' ,and it will be like '12864/1000'.
