### ISSUE TITLE
Crash when opening picker on Android 7.1.2

### ISSUE THREAD

**Issue by bitbendergames** [Sh1d0w/multi_image_picker#282]
**Bug Report**

`multi_image_picker` version: 4.5.8

Is it happening on Android: Yes

Is it happening on iOS: No

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.1069], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
```

**Describe the bug**

When trying to invoke the MultiImagePicker.pickImages method the gallery picker view is briefly visible (without images) before crashing the app with the following stack-trace:

```
W/System  (17694): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework(17694): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
W/art     (17694): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art     (17694): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/art     (17694):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     (17694):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     (17694):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     (17694):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
I/art     (17694):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
I/art     (17694):   at void com.sangcomz.fishbun.ui.album.AlbumActivity.onCreate(android.os.Bundle) (AlbumActivity.java:72)
I/art     (17694):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6723)
I/art     (17694):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     (17694):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2619)
I/art     (17694):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2727)
I/art     (17694):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (17694):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1478)
I/art     (17694):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     (17694):   at void android.os.Looper.loop() (Looper.java:154)
I/art     (17694):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6128)
I/art     (17694):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (17694):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     (17694):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     (17694): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.bitbendergames.colla_gen2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bitbendergames.colla_gen2-1/lib/arm, /data/app/com.bitbendergames.colla_gen2-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
I/art     (17694):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     (17694):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (17694):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (17694):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     (17694):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     (17694):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     (17694):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
I/art     (17694):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
I/art     (17694):   at void com.sangcomz.fishbun.ui.album.AlbumActivity.onCreate(android.os.Bundle) (AlbumActivity.java:72)
I/art     (17694):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6723)
I/art     (17694):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     (17694):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2619)
I/art     (17694):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2727)
I/art     (17694):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (17694):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1478)
I/art     (17694):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     (17694):   at void android.os.Looper.loop() (Looper.java:154)
I/art     (17694):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6128)
I/art     (17694):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (17694):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     (17694):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     (17694): 
E/RecyclerView(17694): No adapter attached; skipping layout
E/AndroidRuntime(17694): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(17694): Process: com.bitbendergames.colla_gen2, PID: 17694
E/AndroidRuntime(17694): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(17694): 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
E/AndroidRuntime(17694): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(17694): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(17694): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(17694): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
E/AndroidRuntime(17694): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(17694): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(17694): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime(17694): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.matches(java.lang.String)' on a null object reference
E/AndroidRuntime(17694): 	at com.sangcomz.fishbun.util.RegexUtil.checkGif(RegexUtil.java:12)
E/AndroidRuntime(17694): 	at com.sangcomz.fishbun.ui.album.AlbumController$LoadAlbumList.doInBackground(AlbumController.java:87)
E/AndroidRuntime(17694): 	at com.sangcomz.fishbun.ui.album.AlbumController$LoadAlbumList.doInBackground(AlbumController.java:48)
E/AndroidRuntime(17694): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
E/AndroidRuntime(17694): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(17694): 	... 4 more
E/flutter (17694): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: The user has cancelled the selection
E/flutter (17694): #0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:73:11)
E/flutter (17694): <asynchronous suspension>
E/flutter (17694): #1      _MyHomePageState.pickImages (package:colla_gen2/main.dart:77:45)
E/flutter (17694): <asynchronous suspension>
E/flutter (17694): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (17694): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (17694): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (17694): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (17694): #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (17694): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (17694): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (17694): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (17694): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (17694): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (17694): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (17694): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (17694): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (17694): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (17694): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (17694): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (17694): #18     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (17694): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

This crash happens on a FairPhone 2, while the same code works both on another Samsung tablet as well as in iOS. Also does not crash in the emulator.

**Comment by Sh1d0w** [comment]
It seems FishBun (the Android image picker I am using in this plugin) crashes. Please report the issue with this stack trace to the official [FishBun repo](https://github.com/sangcomz/FishBun) and once fixed there I will update its version here.
