### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

### ISSUE THREAD

**Issue by benioZhang** [Sh1d0w/multi_image_picker#305]
**Bug Report**

`multi_image_picker` version: 4.5.8

Is it happening on Android: Yes

Is it happening on iOS: 

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 6.2.9200], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Describe the bug**

It may be a bug of FishBun. When i try to pick a photo, it shows all image files, including gif files. If i try to pick a gif file, it will crash.
```
E/AndroidRuntime( 4192): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { (has extras) }} to activity {com.demo.project/com.demo.project.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
E/AndroidRuntime( 4192): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4046)
E/AndroidRuntime( 4192): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4089)
E/AndroidRuntime( 4192): 	at android.app.ActivityThread.access$1400(ActivityThread.java:186)
E/AndroidRuntime( 4192): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
E/AndroidRuntime( 4192): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 4192): 	at android.os.Looper.loop(Looper.java:200)
E/AndroidRuntime( 4192): 	at android.app.ActivityThread.main(ActivityThread.java:5877)
E/AndroidRuntime( 4192): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4192): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4192): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
E/AndroidRuntime( 4192): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/AndroidRuntime( 4192): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
E/AndroidRuntime( 4192): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onActivityResult(MultiImagePickerPlugin.java:666)
E/AndroidRuntime( 4192): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime( 4192): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime( 4192): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 4192): 	at android.app.Activity.dispatchActivityResult(Activity.java:6282)
E/AndroidRuntime( 4192): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4042)
```

**Comment by Sh1d0w** [comment]
Hm that’s strange. On this line I disable gif selection https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L598 so you should not see any gif images in the picker.

In case you see gif images please report this in FishBun repo.
