### ISSUE TITLE
Throw error when select images more than specified max num

### ISSUE THREAD

**Issue by blackredscarf** [Sh1d0w/multi_image_picker#31]
**Describe the bug**
I specified the `maxImages: 3`. If I select the fourth image, throw following error.
```dart
resultList = await MultiImagePicker.pickImages(
      maxImages: 3,
      enableCamera: true,
    );
```
```
W/libEGL  ( 1398): EGLNativeWindowType 0x763b73a010 disconnect failed
W/libEGL  ( 1398): EGLNativeWindowType 0x763b70a010 disconnect failed
V/AudioManager( 1398): playSoundEffect   effectType: 0
V/AudioManager( 1398): playSoundEffect   effectType: 0
V/AudioManager( 1398): playSoundEffect   effectType: 0
V/AudioManager( 1398): playSoundEffect   effectType: 0
D/AndroidRuntime( 1398): Shutting down VM
E/AndroidRuntime( 1398): FATAL EXCEPTION: main
E/AndroidRuntime( 1398): Process: com.zjw.maintainuser, PID: 1398
E/AndroidRuntime( 1398): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
E/AndroidRuntime( 1398): 	at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
E/AndroidRuntime( 1398): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
E/AndroidRuntime( 1398): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
E/AndroidRuntime( 1398): 	at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
E/AndroidRuntime( 1398): 	at android.view.View.performClick(View.java:6291)
E/AndroidRuntime( 1398): 	at android.view.View$PerformClick.run(View.java:24931)
E/AndroidRuntime( 1398): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 1398): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime( 1398): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime( 1398): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/AndroidRuntime( 1398): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1398): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime( 1398): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime( 1398): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/com.zjw.maintainuser-QXLg2Lc07e_wEzQCAZ1XFg==/base.apk"],nativeLibraryDirectories=[/data/app/com.zjw.maintainuser-QXLg2Lc07e_wEzQCAZ1XFg==/lib/arm64, /data/app/com.zjw.maintainuser-QXLg2Lc07e_wEzQCAZ1XFg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
E/AndroidRuntime( 1398): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
E/AndroidRuntime( 1398): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 1398): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 1398): 	... 13 more
I/Process ( 1398): Sending signal. PID: 1398 SIG: 9
Lost connection to device.
```

**Android (please complete the following information):**
 - Device: Huawei P9
 - OS: Android 8.0

**Comment by Sh1d0w** [comment]
Hi, it seems for some reason you are missing the strings file.

Can you please add `strings.xml` following the guide at the bottom here https://github.com/Sh1d0w/multi_image_picker/blob/master/doc/android.md

And let me know if this resolves your issue?

**Comment by blackredscarf** [comment]
@Sh1d0w I add the `res/values/strings.xml` like this, but throws the same error.
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="MissingTranslation">
    <string name="album_name_all">All Media</string>

    <string name="button_preview">Preview</string>
    <string name="button_apply_default">Apply</string>
    <string name="button_apply">Apply(%1$d)</string>
    <string name="button_back">Back</string>
    <string name="photo_grid_capture">Camera</string>
    <string name="empty_text">No media yet</string>
    <string name="button_ok">OK</string>

    <string name="error_over_count_default">You have reached max selectable</string>
    <string name="error_over_count">You can only select up to %1$d media files</string>
    <string name="error_under_quality">Under quality</string>
    <string name="error_over_quality">Over quality</string>
    <string name="error_file_type">Unsupported file type</string>
    <string name="error_type_conflict">Can\'t select images and videos at the same time</string>
    <string name="error_no_video_activity">No App found supporting video preview</string>
    <string name="error_over_original_size">Can\'t select the images larger than %1$d MB</string>
    <string name="error_over_original_count">%1$d images over %2$d MB. Original will be unchecked</string>
    <string name="button_original">Original</string>
    <string name="button_sure_default">Sure</string>
    <string name="button_sure">Sure(%1$d)</string>
</resources>
```

**Comment by Sh1d0w** [comment]
This is a bug in the Android plugin I am using in the picker:

https://github.com/zhihu/Matisse/issues/446

It seems the fix is not yet merged for some reason https://github.com/zhihu/Matisse/pull/521

I will keep eye on it and once it is fixed I will make a new release and will let you know. In the meantime I will look if I can use some temp fixed mirror of this library.

**Comment by Sh1d0w** [comment]
@blackredscarf It seems the fix should be to use those string file I've already sent you but replace

```
<string name="error_over_count">You can only select up to %1$d media files</string>
```

with 

```
<plurals name="error_over_count">
    <item quantity="few">You can only select up to %1$d media file</item>
    <item quantity="many">You can only select up to %1$d media file</item>
    <item quantity="one">You can only select up to 1 media file</item>
    <item quantity="other">You can only select up to %1$d media files</item>
</plurals>
```

Let me know if this resolves it for you, I will update my README as well.

**Comment by blackredscarf** [comment]
@Sh1d0w Good job. It worked.

**Comment by Sh1d0w** [comment]
Great!

**Comment by I-am-original** [comment]
@Sh1d0w i got the same issue. can you share to me the same manual ) where to set settings.xml
