### ISSUE TITLE
Error: The method 'AssetThumbImageProvider.load'

### ISSUE THREAD

**Issue by agnoam** [Sh1d0w/multi_image_picker#323]
**Bug Report**

`multi_image_picker` version: `^4.5.9`

Is it happening on Android: Yes

Is it happening on iOS: didn't check it

```
[√] Flutter (Channel beta, v1.11.0, on Microsoft Windows [Version 10.0.18362.476], locale he-IL)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.40.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Bug description**
    
    #47     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

    build failed.

    FAILURE: Build failed with an exception.

    * Where:
    Script 'c:\Users\admin\Downloads\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 716

    * What went wrong:
    Execution failed for task ':app:compileFlutterBuildDebugArm64'.
    > Process 'command 'c:\Users\admin\Downloads\flutter\bin\flutter.bat'' finished with non-zero exit value 1

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 30s Gradle task assembleDebug failed with exit code 1

**Comment by Sh1d0w** [comment]
Hi, I see nothing regarding `multi_image_picker` in your bug message. Please provide the full stack trace with the error, otherwise I can't help you.

Make sure your project is migrated to AndroidX before using the plugin, as described in the docs.

**Comment by agnoam** [comment]
I'm sorry, I missed the start of the logs.

````
Launching lib\main.dart on Mi A1 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.5.9/lib/src/asset_thumb_provider.dart:31:24: Error: The method 'AssetThumbImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AssetThumbImageProvider key) {
                       ^
../../Downloads/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:213:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
<asynchronous suspension>
#7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:154:50)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:556:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:222:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:50:10)
#44     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#45     main (file:///c:/Users/joe/Downloads/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\joe\Downloads\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 716

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command 'C:\Users\joe\Downloads\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Finished with error: Gradle task assembleDebug failed with exit code 1
````

Please check again.

**Comment by Sh1d0w** [comment]
You are not using the stable version of Flutter. Version 4.5.9 of the plugin supports only the stable version.

The error you are getting is fixed in version 4.6.0-rc.3 which supports Flutter unstable channel.

**Comment by agnoam** [comment]
how do I get version `4.6.0-rc.3` ?

**Comment by Sh1d0w** [comment]
Change the version in your pubspec.yaml file.

**Comment by agnoam** [comment]
I tried this: `multi_image_picker: 4.6.0`, but it didn't work. So what should I do ?

**Comment by Sh1d0w** [comment]
There is not such version `4.6.0`, put the version that I gave you.

`multi_image_picker: 4.6.0-rc.3`

**Comment by agnoam** [comment]
Thanks a lot... this was very helpful. 

By the way, why isn't this shown as the latest version in `pub.dev` ?

**Comment by Sh1d0w** [comment]
No worries.

It is shown there, but as Release Candidate version, next to the official one, see the screenshot. 


<img width="457" alt="Screenshot 2019-11-25 at 16 03 02" src="https://user-images.githubusercontent.com/5074917/69546789-1122d900-0f9d-11ea-9fb2-a2cd9792914d.png">
