### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by harloom** [Sh1d0w/multi_image_picker#340]
```
E/AndroidRuntime(25851): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
E/AndroidRuntime(25851): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
E/AndroidRuntime(25851): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(25851): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
E/AndroidRuntime(25851): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25851): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(25851): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime(25851): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25851): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime(25851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/AndroidRuntime(25851): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25851): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/AndroidRuntime(25851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:235)
E/AndroidRuntime(25851): 	at com.leeson.image_pickers.ImagePickersPlugin$1.onActivityResult(ImagePickersPlugin.java:66)
E/AndroidRuntime(25851): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(25851): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(25851): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(25851): 	at android.app.Activity.dispatchActivityResult(Activity.java:6915)
E/AndroidRuntime(25851): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
```

  page_view_indicators: ^1.3.0
  video_player: ^0.10.4+1
  multi_image_picker: ^4.5.9
  image_pickers: ^1.0.6

maybe duplicate image_pickers

**Comment by Sh1d0w** [comment]
As seen from the stack trace, the error is related the other plugin not mine:

```
com.leeson.image_pickers.ImagePickersPlugin$1.onActivityResult(ImagePickersPlugin.java:66)
```
