### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by yuefeng007** [Sh1d0w/multi_image_picker#411]
**Bug Report**

`multi_image_picker` version: 
multi_image_picker: ^4.6.3
Is it happening on iOS: Yes 

```
 <!-- run `flutter doctor` and paste the output here: -->
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95,
    locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)
```

**Describe the bug**

```
bogon:demo a$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                                  
  133.2s (!)                                       
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A multi_image_picker
      - Flutter
      - amap_core_fluttify
      - amap_location_fluttify
      - city_pickers
      - flutter_plugin_android_lifecycle
      - flutter_sound
      - flutter_splash_screen
      - fluttertoast
      - foundation_fluttify
      - image_crop
      - image_picker
      - path_provider
      - path_provider_macos
      - permission_handler
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - tencent_im_plugin
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `amap_core_fluttify` from
    `.symlinks/plugins/amap_core_fluttify/ios`
    -> Fetching podspec for `amap_location_fluttify` from
    `.symlinks/plugins/amap_location_fluttify/ios`
    -> Fetching podspec for `city_pickers` from
    `.symlinks/plugins/city_pickers/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from
    `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_sound` from
    `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `flutter_splash_screen` from
    `.symlinks/plugins/flutter_splash_screen/ios`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `foundation_fluttify` from
    `.symlinks/plugins/foundation_fluttify/ios`
    -> Fetching podspec for `image_crop` from `.symlinks/plugins/image_crop/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `multi_image_picker` from
    `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from
    `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `tencent_im_plugin` from
    `.symlinks/plugins/tencent_im_plugin/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_f_f.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_e_0.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/7/e/0/BSImagePicker/3.1.1/BSImagePicker.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_0.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_d_3.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/d/3/HandyJSON/5.0.2-beta/HandyJSON.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/7/e/0/BSImagePicker/2.10.3/BSImagePicker.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_4_b_c.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Redirecting from
      https://cdn.cocoapods.org/Specs/4/b/c/BSImageView/1.0.0/BSImageView.podspe
      c.json to
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.0/BSImageView.podspec.json
      CDN: trunk Redirecting from
      https://cdn.cocoapods.org/Specs/4/b/c/BSImageView/1.0.2/BSImageView.podspe
      c.json to
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.2/BSImageView.podspec.json
      CDN: trunk Redirecting from
      https://cdn.cocoapods.org/Specs/4/b/c/BSImageView/1.0.3/BSImageView.podspe
      c.json to
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.3/BSImageView.podspec.json
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.0/BSImageView.podspec.json Response: Timeout was reached,
      retries: 4
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.2/BSImageView.podspec.json Response: Timeout was reached,
      retries: 4
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.3/BSImageView.podspec.json Response: Timeout was reached,
      retries: 4
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.0/BSImageView.podspec.json Response: Timeout was reached,
      retries: 3
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.2/BSImageView.podspec.json Response: Timeout was reached,
      retries: 3
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.3/BSImageView.podspec.json Response: Timeout was reached,
      retries: 3
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.0/BSImageView.podspec.json Response: Timeout was reached,
      retries: 2
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.2/BSImageView.podspec.json Response: Timeout was reached,
      retries: 2
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.3/BSImageView.podspec.json Response: Timeout was reached,
      retries: 2
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.0/BSImageView.podspec.json Response: Timeout was reached,
      retries: 1
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.2/BSImageView.podspec.json Response: Timeout was reached,
      retries: 1
      CDN: trunk URL couldn't be downloaded:
      https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSIma
      geView/1.0.3/BSImageView.podspec.json Response: Timeout was reached,
      retries: 1
    [!] CDN: trunk Repo update failed - 3 error(s):
    CDN: trunk URL couldn't be downloaded:
    https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSImage
    View/1.0.0/BSImageView.podspec.json Response: Timeout was reached
    CDN: trunk URL couldn't be downloaded:
    https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSImage
    View/1.0.2/BSImageView.podspec.json Response: Timeout was reached
    CDN: trunk URL couldn't be downloaded:
    https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/b/c/BSImage
    View/1.0.3/BSImageView.podspec.json Response: Timeout was reached

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_so
    urce.rb:475:in `rescue in concurrent_requests_catching_errors'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_so
    urce.rb:470:in `concurrent_requests_catching_errors'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_so
    urce.rb:121:in `versions'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specif
    ication/set.rb:99:in `block in versions_by_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specif
    ication/set.rb:98:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specif
    ication/set.rb:98:in `each_with_object'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specif
    ication/set.rb:98:in `versions_by_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specif
    ication/set.rb:56:in `specification_name'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_so
    urce.rb:216:in `search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source
    /aggregate.rb:83:in `block in search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source
    /aggregate.rb:83:in `select'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source
    /aggregate.rb:83:in `search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:416:
    in `create_set_from_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:385:
    in `find_cached_set'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:
    in `specifications_for_dependency'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:
    in `search_for'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:
    in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `sort_by'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:75
    4:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:74
    6:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:72
    9:in `activate_new_spec'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:68
    6:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:25
    4:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:18
    2:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:i
    n `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:i
    n `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410
    :in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235
    :in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234
    :in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156
    :in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.
    rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro Max.
```

**Comment by yuefeng007** [comment]
1.Do flutter clean

2.Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update
