### ISSUE TITLE
android crash on Honor v10 android 10

### ISSUE THREAD

**Issue by sunpulun** [Sh1d0w/multi_image_picker#426]
**Bug Report**

`multi_image_picker` version: 4.6.5+rc1

Is it happening on Android: YES

Is it happening on iOS: No

**Describe the bug**
MultiImagePickerPlugin
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { (has extras) }} to activity {cn.sm.flutter_hhk/cn.sm.flutter_hhk.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5462)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5503)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onActivityResult(MultiImagePickerPlugin.java:568)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
        at android.app.Activity.dispatchActivityResult(Activity.java:8413)

**Comment by Sh1d0w** [comment]
This error happens when there is a conflict with another plugin you are using. See the following similar issues https://github.com/Sh1d0w/multi_image_picker/issues?q=is%3Aissue+ResultInfo%7B
