### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method

### ISSUE THREAD

**Issue by anisalibegic** [Sh1d0w/multi_image_picker#445]
**Bug Report**

`multi_image_picker` version: latest (4.6.6+rc.1)

Is it happening on Android: Yes

Is it happening on iOS: Not sure

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale bs-Latn-BA)
    • Flutter version 1.12.13+hotfix.9 at C:\Programs\Flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Anis\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Anis\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • ANE LX1 • 9WV4C19131006232 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Describe the bug**

Crashlytics informed me that there are some stability issues with my app (2 crashes on 2 devices).
They gave me a stack trace when the crash occured and I think it's connected with this package since this is the only image picker plugin that I'm using in my app (which is using AndroidX).

Full stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.sangcomz.fishbun.k.a.a.b(android.widget.ImageView, android.net.Uri)' on a null object reference
       at com.sangcomz.fishbun.adapter.view.PickerGridAdapter.b(PickerGridAdapter.java:121)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java)
       at androidx.recyclerview.widget.RecyclerView$Adapter.a(RecyclerView.java:29)
       at androidx.recyclerview.widget.RecyclerView$Recycler.a(RecyclerView.java:39)
       at androidx.recyclerview.widget.RecyclerView$Recycler.a(RecyclerView.java:503)
       at androidx.recyclerview.widget.RecyclerView$Recycler.b(RecyclerView.java:5)
       at androidx.recyclerview.widget.RecyclerView$Recycler.d(RecyclerView.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(LinearLayoutManager.java:11)
       at androidx.recyclerview.widget.GridLayoutManager.a(GridLayoutManager.java:96)
       at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:38)
       at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:334)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:9)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:38)
       at androidx.recyclerview.widget.RecyclerView.c(RecyclerView.java:37)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.b(HeaderScrollingViewBehavior.java:135)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:42)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:788)
       at android.view.View.layout(View.java:19814)
       at android.view.ViewGroup.layout(ViewGroup.java:6150)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2605)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2310)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1446)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7014)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:916)
       at android.view.Choreographer.doCallbacks(Choreographer.java:728)
       at android.view.Choreographer.doFrame(Choreographer.java:660)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:902)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {app.id/com.sangcomz.fishbun.ui.picker.PickerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=128, result=-1, data=null} to activity {app.id/com.sangcomz.fishbun.ui.picker.PickerActivity}: java.lang.NullPointerException: Attempt to get length of null array
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4430)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

```
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=128, result=-1, data=null} to activity {app.id/com.sangcomz.fishbun.ui.picker.PickerActivity}: java.lang.NullPointerException: Attempt to get length of null array
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4409)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

```
Caused by java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Collections.addAll(Collections.java:5460)
       at com.sangcomz.fishbun.adapter.view.PickerGridAdapter.a(PickerGridAdapter.java:11)
       at com.sangcomz.fishbun.ui.picker.PickerActivity.onActivityResult(PickerActivity.java:34)
       at android.app.Activity.dispatchActivityResult(Activity.java:7797)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4409)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Device specification**
Brand: _UMIDIGI_
Model: _A3_
Orientation: _Portrait_
RAM free: _462.2 MB_
Disk free: _757.43 MB_

**Operating System**
Version: _8.1.0_
Orientation: _Portrait_
Rooted: _No_

**Comment by dheeraj2dj** [comment]
Same case for one of my users as well

<img width="976" alt="Screenshot 2020-06-01 at 11 53 23 PM" src="https://user-images.githubusercontent.com/2561485/83440760-19376600-a463-11ea-80aa-5ff1e73a557e.png">

### multi_image_picker: 4.6.7

**Device Info**
Brand: Xiaomi
Model: Redmi Note 8
Orientation: Portrait
RAM free: 979.75 MB
Disk free: 15.67 GB

**Operating System**
Version: 9
Orientation: Portrait
Rooted: No

<details>
<summary>
flutter doctor -v
</summary>

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.2 at /Users/dheeraj2dj/flutter
    • Framework revision 5f21edf8b6 (4 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dheeraj2dj/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>


<details>
<summary>Stack trace:</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.sangcomz.fishbun.k.a.a.b(android.widget.ImageView, android.net.Uri)' on a null object reference
       at com.sangcomz.fishbun.adapter.view.PickerGridAdapter.b(PickerGridAdapter.java:121)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java)
       at androidx.recyclerview.widget.RecyclerView$Adapter.a(RecyclerView.java:29)
       at androidx.recyclerview.widget.RecyclerView$Recycler.a(RecyclerView.java:39)
       at androidx.recyclerview.widget.RecyclerView$Recycler.a(RecyclerView.java:503)
       at androidx.recyclerview.widget.RecyclerView$Recycler.b(RecyclerView.java:5)
       at androidx.recyclerview.widget.RecyclerView$Recycler.d(RecyclerView.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(LinearLayoutManager.java:11)
       at androidx.recyclerview.widget.GridLayoutManager.a(GridLayoutManager.java:96)
       at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:38)
       at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:334)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:9)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:38)
       at androidx.recyclerview.widget.RecyclerView.c(RecyclerView.java:37)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.b(HeaderScrollingViewBehavior.java:135)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:42)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
       at android.view.View.layout(View.java:20699)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2876)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2393)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1535)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7405)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
       at android.view.Choreographer.doCallbacks(Choreographer.java:839)
       at android.view.Choreographer.doFrame(Choreographer.java:774)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

</details>
