### ISSUE TITLE
Crashed on  MultiImagePicker.pickImages when import flutter_sound_lite: ^4.0.0

### ISSUE THREAD

**Issue by iyuhang** [Sh1d0w/multi_image_picker#446]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 
YES

Is it happening on iOS: 
NO

```
 <!-- run `flutter doctor` and paste the output here: -->
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)
```

**Describe the bug**

when import flutter_sound_lite: ^4.0.0, 

crashed on  MultiImagePicker.pickImages 

crash log:

```
04-26 13:58:23.140 I/ActivityTaskManager( 1522): START u0 {cmp=com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity} from uid 10665 pid 25652
04-26 13:58:23.150 D/OpRestartProcessManager( 1522): updateSelf :  com.fixtime.yuyu, size : 17
04-26 13:58:23.150 E/ScreenModeService( 1522): getAppToken AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}}
04-26 13:58:23.150 E/ScreenModeService( 1522): setRefreshRate token AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}} rate 0
04-26 13:58:23.150 D/OpQuickReply( 1522): setQuickReplyResumed focusedApp AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}} pkgName com.fixtime.yuyu
04-26 13:58:23.152 I/OpMotorManagerService( 1522): notifyActivityChanged: mBackgroudPkg = com.fixtime.yuyu mFocusPkg = com.fixtime.yuyu mIsSplitMode = false mBackActivity = com.fixtime.yuyu mFocusActivity = com.sangcomz.fishbun.ui.album.AlbumActivity
04-26 13:58:23.219 E/AndroidRuntime(25652): FATAL EXCEPTION: main
04-26 13:58:23.219 E/AndroidRuntime(25652): Process: com.fixtime.yuyu, PID: 25652
04-26 13:58:23.219 E/AndroidRuntime(25652): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/TintableCompoundDrawablesView;
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1383)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2151)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2708)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2775)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2129)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.sangcomz.fishbun.ui.album.AlbumActivity.onCreate(AlbumActivity.java:75)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Activity.performCreate(Activity.java:7820)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Activity.performCreate(Activity.java:7809)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3362)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3526)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2122)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.os.Looper.loop(Looper.java:214)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
04-26 13:58:23.219 E/AndroidRuntime(25652): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.widget.TintableCompoundDrawablesView" on path: DexPathList[[zip file "/data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/base.apk"],nativeLibraryDirectories=[/data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/lib/arm64, /data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	... 32 more
04-26 13:58:24.480 I/DropBoxManagerService( 1522): add tag=data_app_crash isTagEnabled=true flags=0x2
04-26 13:58:24.480 W/ActivityTaskManager( 1522):   Force finishing activity com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity
04-26 13:58:24.481 W/ActivityTaskManager( 1522):   Force finishing activity com.fixtime.yuyu/com.example.fixtime.MainActivity
```

**Comment by iyuhang** [comment]
@Sh1d0w , also reported in https://github.com/dooboolab/flutter_sound/issues/323

**Comment by Sh1d0w** [comment]
Hi, did you migrate your project to Android X, as described in the docs?

**Comment by iyuhang** [comment]
yes, migrated , It runs well before I import the flutter_sound plugin, and if I remove flutter_sound, no crash

**Comment by iyuhang** [comment]
@Sh1d0w any ideas ? help me

**Comment by Sh1d0w** [comment]
Sure I will check later as currently I am no my phone.

Can you check if it happens on the example app in this repo meanwhile?

**Comment by iyuhang** [comment]
It seems no problem on the example app, oh

**Comment by Sh1d0w** [comment]
In that case you need to provide an example repository which I can checkout and run so I can reproduce.

Please also double check you correctly and successfully migrated to Android X as this error seems to be caused by this according to the message.

**Comment by iyuhang** [comment]
Okay, thanks, I will check that


 
---Original---

**Comment by iyuhang** [comment]
// subprojects {
//     project.configurations.all {
//         resolutionStrategy.eachDependency { details ->
//             if (details.requested.group == 'androidx.core' &&
//                     !details.requested.name.contains('androidx')) {
//                 details.useVersion "1.0.1"
//             }
//         }
//     }
// }

Finally, removed the above code in android/build.gradle solved this issue.
