### ISSUE TITLE
Bug: outOfMemory with large pictures

### ISSUE THREAD

**Issue by salim-lachdhaf** [Sh1d0w/multi_image_picker#448]
**Describe the bug**
If we select a large image the app crashes with this error:

> java.lang.OutOfMemoryError: Failed to allocate a

...

**To Reproduce**
1. download this example image from [here](https://ibb.co/XzpnDNX) : 
1. Select that image or any other large image (for example 9mb size, 14500x7000)
2. Click on 'done'
3. App crashes

**Smartphone :**
 - FishBun version: 0.11.2
 - Device: Samsung Tab 10
 - OS: Android 9
 - IOS: Not tested

**Comment by anisalibegic** [comment]
I'm having the same problem. 

**Device**
_Brand_: samsung
_Model_: Galaxy S5
_Orientation_: Portrait
_RAM free_: 341.95 MB
_Disk free_: 559.84 MB

**Operating System**
_Version_: 6.0.1
_Orientation_: Portrait
_Rooted_: No

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 63489036 byte allocation with 16766704 free bytes and 43MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin.finishWithSuccess(MultiImagePickerPlugin.java)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin.access$000(MultiImagePickerPlugin.java)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.doInBackground(MultiImagePickerPlugin.java)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.doInBackground(MultiImagePickerPlugin.java)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Sh1d0w** [comment]
Please provide example code which I can run and reproduce. It does matter how you structure your code. As the docs describe you should never request image data in loops etc, as each call to get the byte data allocates memory.

I've tried the image you've posted in the example app of this repo and was not able to reproduce the error.

![ezgif-3-888b0371b8e8](https://user-images.githubusercontent.com/5074917/80491181-0a90f700-896b-11ea-8aa7-3243dfae3214.gif)

**Comment by anisalibegic** [comment]
I used posted image with the example project on some older tablet and it crashed when clicking done. It looks like it crashes on older devices with less RAM.

**Device**
_Brand_: samsung
_Model_: Galaxy Tab E
_Orientation_: Portrait

**Operating System**
_Version_: 4.4.4
_Orientation_: Portrait
_Rooted_: No

**Comment by anisalibegic** [comment]
I have to correct myself. In the example application everything is working great until `getByteData()` is called. As soon as I call `getByteData()` application crashes with the `E/dalvikvm-heap( 9065): Out of memory on a 462559272-byte allocation` error. It even crashes when using `quality: 1`. 

![ezgif-3-d1a31b7abc79](https://user-images.githubusercontent.com/12012869/80503179-cead6000-8971-11ea-9d93-aed8504515de.gif)

PS: `Nažalost, aplikacija example prekinula je s radom.` means `Unfortunately, the example application stopped working.`.

**Comment by salim-lachdhaf** [comment]
I tested either with the native lib FishBun and it crashes also.

**Comment by Sh1d0w** [comment]
Thanks for debugging it further @salim-lachdhaf . In that case could you please open an issue in FishBun repo? Once the owner fixes the issue I will update the plugin immediately.

Thanks.

**Comment by jacobokoenig** [comment]
> I've tried the image you've posted in the example app of this repo and was not able to reproduce the error.

How would you suggest we upload several pictures to the server if loop is not appropriate? Thanks!
