### ISSUE TITLE
add    multi_image_picker: ^4.6.7 ,  error

### ISSUE THREAD

**Issue by kangshibiao123** [Sh1d0w/multi_image_picker#454]
add    multi_image_picker: ^4.6.7 ,  error
 remove multi_image_picker  success
pod search BSImagePicker noResponse ， gitHubCanBeOpened
error log
faith:ios faith$ pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/faith/.rvm/gems/ruby-2.4.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /Users/faith/.rvm/rubies/ruby-2.4.1/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ 493b92746da8a2e0c0cd8fa0025108d5c009b90b

               FaithSpec - git - git@gitee.com:ksbzxcode/NIMLiveDemo.git @ 3c136af46d029211fbeb8275c13e9bf9148bcf4d

               master - file system
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
JSON::ParserError - 743: unexpected token at ''
/Users/faith/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/Users/faith/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/faith/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:340:in `block in delegating_block'
/Users/faith/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:341:in `block in delegating_block'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/faith/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/faith/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/faith/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/faith/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/faith/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=743%3A+unexpected+token+at+%27%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - JSON::ParserError - 743: unexpected token at ''
   https://github.com/CocoaPods/CocoaPods/issues/9311 [closed] [2 comments]
   01 Nov 2019

 - Pod search error 
   https://github.com/CocoaPods/CocoaPods/issues/6407 [closed] [4 comments]
   11 Apr 2018

**Comment by Sh1d0w** [comment]
That seems strange, the error appears to be coming from Cocoapods, not able to find BSImagePicker. Maybe check your firewall or try to remove and re-add the plugin.

**Comment by kangshibiao123** [comment]
It is useless to open the VPN, and everything else is normal, such as FMDB,
