### ISSUE TITLE
crash when call pickImages function

### ISSUE THREAD

**Issue by linguitang** [Sh1d0w/multi_image_picker#46]
`I/Timeline(27876): Timeline: Activity_launch_request time:7917446
W/art     (27876): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AndroidRuntime(27876): Shutting down VM
E/AndroidRuntime(27876): FATAL EXCEPTION: main
E/AndroidRuntime(27876): Process: com.example.client, PID: 27876
E/AndroidRuntime(27876): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.client/com.zhihu.matisse.ui.MatisseActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayShowTitleEnabled(boolean)' on a null object reference
E/AndroidRuntime(27876): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
E/AndroidRuntime(27876): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
E/AndroidRuntime(27876): 	at android.app.ActivityThread.access$1100(ActivityThread.java:156)
E/AndroidRuntime(27876): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
E/AndroidRuntime(27876): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27876): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(27876): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime(27876): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27876): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
E/AndroidRuntime(27876): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
E/AndroidRuntime(27876): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayShowTitleEnabled(boolean)' on a null object reference
E/AndroidRuntime(27876): 	at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:120)
E/AndroidRuntime(27876): 	at android.app.Activity.performCreate(Activity.java:6362)
E/AndroidRuntime(27876): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
E/AndroidRuntime(27876): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
E/AndroidRuntime(27876): 	... 9 more
I/Process (27876): Sending signal. PID: 27876 SIG: 9`

**Comment by linguitang** [comment]
android 6.0.1  
multi_image_picker 2.3.26

**Comment by linguitang** [comment]
I clear build folder，rebuild project，it works ok now，thanks！
