### ISSUE TITLE
This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

### ISSUE THREAD

**Issue by QEout** [Sh1d0w/multi_image_picker#460]
I  tried to change my styles.xml and AndroidManifest，but still.
`2020-05-13 14:07:34.996 13850-13850/top.aengus.lalia E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.aengus.lalia, PID: 13850
    java.lang.RuntimeException: Unable to start activity ComponentInfo{top.aengus.lalia/com.sangcomz.fishbun.ui.album.AlbumActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:411)
        at androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:150)
        at com.sangcomz.fishbun.ui.album.AlbumActivity.initToolBar(AlbumActivity.java:130)
        at com.sangcomz.fishbun.ui.album.AlbumActivity.initView(AlbumActivity.java:106)
        at com.sangcomz.fishbun.ui.album.AlbumActivity.onCreate(AlbumActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
2020-05-13 14:07:34.998 1640-1791/? W/ActivityManager:   Force finishing activity top.aengus.lalia/com.sangcomz.fishbun.ui.album.AlbumActivity
2020-05-13 14:07:35.000 1640-1791/? W/ActivityManager:   Force finishing activity top.aengus.lalia/.MainActivity
2020-05-13 14:07:35.002 1640-1657/? I/ActivityManager: Showing crash dialog for package top.aengus.lalia u0
2020-05-13 14:07:35.026 1640-7435/? I/OpenGLRenderer: Initialized EGL, version 1.4
2020-05-13 14:07:35.026 1640-7435/? D/OpenGLRenderer: Swap behavior 1
2020-05-13 14:07:35.027 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2654208
2020-05-13 14:07:35.037 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2654208
2020-05-13 14:07:35.039 1640-7435/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2020-05-13 14:07:35.039 1640-7435/? D/OpenGLRenderer: Swap behavior 0
2020-05-13 14:07:35.049 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2654208
2020-05-13 14:07:35.054 1640-7435/? D/EGL_emulation: eglCreateContext: 0xb6a22e20: maj 2 min 0 rcv 2
2020-05-13 14:07:35.067 1640-7435/? D/EGL_emulation: eglMakeCurrent: 0xb6a22e20: ver 2 0 (tinfo 0xa69ff770)
2020-05-13 14:07:35.214 1640-1657/? W/Looper: Dispatch took 156ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {44f57fc} cb=android.view.Choreographer$FrameDisplayEventReceiver@b7f6e85 msg=0
2020-05-13 14:07:35.436 1406-1406/? I/qemu-props: start adbd ...
2020-05-13 14:07:35.501 1640-1656/? W/ActivityManager: Activity pause timeout for ActivityRecord{d4ae7b3 u0 top.aengus.lalia/com.sangcomz.fishbun.ui.album.AlbumActivity t132 f}
2020-05-13 14:07:35.540 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2020-05-13 14:07:35.553 1399-1399/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
2020-05-13 14:07:35.574 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2020-05-13 14:07:35.596 2141-2385/? D/EGL_emulation: eglMakeCurrent: 0xa67ffd00: ver 2 0 (tinfo 0xa6a7fcc0)
2020-05-13 14:07:35.598 1408-1408/? D/SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
2020-05-13 14:07:35.616 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2020-05-13 14:07:35.637 1399-1399/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
2020-05-13 14:07:35.651 1399-1399/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2020-05-13 14:07:35.691 2141-2141/? W/SessionLifecycleManager: Handover failed. Creating new session controller.
2020-05-13 14:07:35.694 2141-2141/? I/OptInState: There is a new client and it does not support opt-in. Dropping request.
2020-05-13 14:07:35.710 2176-2267/? D/EGL_emulation: eglMakeCurrent: 0xa9185c00: ver 2 0 (tinfo 0xa91838f0)
2020-05-13 14:07:35.772 1751-1980/? D/EGL_emulation: eglMakeCurrent: 0x95b62460: ver 2 0 (tinfo 0x95b1e0f0)
2020-05-13 14:07:36.005 1640-1656/? I/ActivityManager: Killing 9935:android.process.media/u0a11 (adj 906): empty for 5407s
2020-05-13 14:07:36.217 2176-2267/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
2020-05-13 14:07:46.004 1640-1656/? W/ActivityManager: Activity destroy timeout for ActivityRecord{d4ae7b3 u0 top.aengus.lalia/com.sangcomz.fishbun.ui.album.AlbumActivity t132 f}
2020-05-13 14:07:46.007 1640-1656/? W/ActivityManager: Activity destroy timeout for ActivityRecord{1e550cf u0 top.aengus.lalia/.MainActivity t132 f}
2020-05-13 14:07:49.977 1640-1655/? E/memtrack: Couldn't load memtrack module`

**Comment by QEout** [comment]
Can you help me? Thank you very very much.
