### ISSUE TITLE
enableCamera feature is crashing

### ISSUE THREAD

**Issue by jawand** [Sh1d0w/multi_image_picker#47]
**Describe the bug**
on click of camera icon. Application crashes.

**To Reproduce**
I am using this repository example app. 

```
import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:multi_image_picker/multi_image_picker.dart';
import 'asset_view.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Asset> images = List<Asset>();
  String _error;

  @override
  void initState() {
    super.initState();
  }

  Widget buildGridView() {
    return GridView.count(
      crossAxisCount: 3,
      children: List.generate(images.length, (index) {
        return AssetView(index, images[index]);
      }),
    );
  }

  Future<void> loadAssets() async {
    setState(() {
      images = List<Asset>();
    });

    List<Asset> resultList;
    String error;

    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 10,
        enableCamera: true,
        options: CupertinoOptions(takePhotoIcon: "chat"),
      );
    } on PlatformException catch (e) {
      error = e.message;
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      images = resultList;
      if (error == null) _error = 'No Error Dectected';
    });
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Column(
          children: <Widget>[
            Center(child: Text('Error: $_error')),
            RaisedButton(
              child: Text("Pick images"),
              onPressed: loadAssets,
            ),
            Expanded(
              child: buildGridView(),
            )
          ],
        ),
      ),
    );
  }
}

```

**Expected behavior**
on click of camera icon it should work.

**Debug Output**

```
W/art     (17937): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
V/BoostFramework(17937): BoostFramework() : mPerf = com.qualcomm.qti.Performance@3c726e
V/BoostFramework(17937): BoostFramework() : mPerf = com.qualcomm.qti.Performance@3ae6d0f
I/art     (17937): Do partial code cache collection, code=25KB, data=30KB
I/art     (17937): After code cache collection, code=24KB, data=29KB
I/art     (17937): Increasing code cache capacity to 128KB
D/AndroidRuntime(17937): Shutting down VM
E/AndroidRuntime(17937): FATAL EXCEPTION: main
E/AndroidRuntime(17937): Process: com.example.fluttergallerymultiple, PID: 17937
E/AndroidRuntime(17937): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/AndroidRuntime(17937): 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
E/AndroidRuntime(17937): 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
E/AndroidRuntime(17937): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
E/AndroidRuntime(17937): 	at com.zhihu.matisse.internal.utils.MediaStoreCompat.dispatchCaptureIntent(MediaStoreCompat.java:86)
E/AndroidRuntime(17937): 	at com.zhihu.matisse.ui.MatisseActivity.capture(MatisseActivity.java:424)
E/AndroidRuntime(17937): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter$1.onClick(AlbumMediaAdapter.java:75)
E/AndroidRuntime(17937): 	at android.view.View.performClick(View.java:5647)
E/AndroidRuntime(17937): 	at android.view.View$PerformClick.run(View.java:22462)
E/AndroidRuntime(17937): 	at android.os.Handler.handleCallback(Handler.java:754)
E/AndroidRuntime(17937): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17937): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime(17937): 	at android.app.ActivityThread.main(ActivityThread.java:6221)
E/AndroidRuntime(17937): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17937): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(17937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Lost connection to device.
Exited (sigterm)
```

**Screenshots**
![screenshot_2018-12-26-17-05-37-338_com google android packageinstaller](https://user-images.githubusercontent.com/34437706/50444874-e6657600-0930-11e9-9207-1eb0fa6c1fd0.png)
![screenshot_2018-12-26-17-05-41-578_com google android packageinstaller](https://user-images.githubusercontent.com/34437706/50444875-e6657600-0930-11e9-8211-fd6c31efb555.png)
![screenshot_2018-12-26-17-05-53-033_com example fluttergallerymultiple](https://user-images.githubusercontent.com/34437706/50444873-e6657600-0930-11e9-8c5f-aefe4c455e05.png)

**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: [e.g. 2.0.04]
2.3.27
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.30.1)
[√] Connected device (2 available)

• No issues found!
```

**iOS (please complete the following information):**
Not tested on iOS.

**Android (please complete the following information):**
 - Device: Redmi 4A
 - OS: 7.1

**Additional context**
tried on Moto G5 as well. But same error. It has OS 8.1

**Comment by Sh1d0w** [comment]
Hi, have you followed the instructions here https://sh1d0w.github.io/multi_image_picker/#/enablecamera?id=enable-camera-on-android ?

**Comment by jawand** [comment]
I am really sorry. I missed it some how. It is working fine. Thanks a lot for this library.
I have one more question. 

when user click on camera button and captures an image and accept that image. How can i stay in gallery page only. Instead of coming back to home page.

**Comment by jawand** [comment]
btw in old issues there is old url  https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery

which is misleading.

**Comment by Sh1d0w** [comment]
@jawand Yeah that file was removed because now I've created this dedicated docs website, which you can see in the README. It is better as it has search functionality and is more readable.

Regarding you question, this is how the native Android plugin I am using works https://github.com/zhihu/Matisse

If you want to request this feature, you have to do it there. The iOS plugins works exactly as you like.
