### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by kw2019ltd** [Sh1d0w/multi_image_picker#501]
Caused by java.lang.NullPointerException: Attempt to get length of null array

Caused by java.lang.NullPointerException: Attempt to get length of null array
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.doInBackground(MultiImagePickerPlugin.java:193)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.doInBackground(MultiImagePickerPlugin.java:154)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

![image](https://user-images.githubusercontent.com/47334522/87640344-3c864e00-c74f-11ea-9b3a-a2dd449d6e73.png)

**Comment by LuanVna** [comment]
I have the same issue, someone could help me to fix it?

**Comment by zhancheng** [comment]
same issue

**Comment by kw2019ltd** [comment]
added PR 
https://github.com/Sh1d0w/multi_image_picker/pull/591/files
