### ISSUE TITLE
Reply already submitted 

### ISSUE THREAD

**Issue by krngd2** [Sh1d0w/multi_image_picker#52]
Just installed the plugin, when ran it It failed to build for android, gone through the issues and fixed it by changing the build version (26.0.1 to 27.1.1) in project gradle build file 
```
project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
```

then app build succesfull but when i click the button this error is showing and nothing happens.

> /MethodChannel#multi_image_picker(18196): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
> E/MethodChannel#multi_image_picker(18196): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
> E/MethodChannel#multi_image_picker(18196): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#multi_image_picker(18196): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/MethodChannel#multi_image_picker(18196): 	at android.os.Looper.loop(Looper.java:142)
> E/MethodChannel#multi_image_picker(18196): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
> E/MethodChannel#multi_image_picker(18196): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#multi_image_picker(18196): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/MethodChannel#multi_image_picker(18196): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**To Reproduce**

```
<!-- Insert example code here, that will help to reproduce the bug -->
```

**Expected behavior**

**Screenshots**

**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: [e.g. 2.0.04]

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**iOS (please complete the following information):**
 - Swift Version: [e.g. 4.0]

**Android (please complete the following information):**
 - Device: [e.g. Nexus 5]
 - OS: [e.g. Lollipop 5.1]

**Additional context**

**Comment by Sh1d0w** [comment]
Hi, please provide the output from `flutter doctor` and let me know what Android version does your device has?

Also please try to run the example app in this repo and let me know if you can run it successfully or you get the same error?

**Comment by Sh1d0w** [comment]
PS. Are you somehow clicking the button twice fast? From what I see you are trying to invoke the image picker after it was opened again, that's why it crashes. I will need a steps to reproduce it before I can fix it correctly.

**Comment by krngd2** [comment]
To be sure I have checked it now, First click nothing happens, on Second click error is showing.  Added  read and write external storage permission at AndroidManifist.xml still nothing happens on first click, first clicked and waited for few secs still nothing, showing the same error on second click

**Comment by Sh1d0w** [comment]
I see, ok. Can you tell me which Android version you are trying to run it on?

**Comment by krngd2** [comment]
Android :

Device: Asus Zenfone max pro m1 6gb ram
OS: 8.1.0 stock android

**Comment by Sh1d0w** [comment]
I will release a fix soon and will let you know. Thanks for the report.

**Comment by krngd2** [comment]
Thank you for the quick response.

**Comment by krngd2** [comment]
Hey Thank you very much for the quick fix, I upgraded to version 2.3.29 and ran it, now it happens nothing when I click the button but I got 

> I/SimplePermission(7572): Requesting permission status : 0

i have Simple Permissions plugin installed so i thought it might be permission issue, then i wrote a check permission function 
  ```
Future<bool> requestStoragePermission(){ 
    return SimplePermissions.checkPermission(Permission.ReadExternalStorage).then((onValue)=>
      !onValue ? SimplePermissions.requestPermission(Permission.ReadExternalStorage).then((onValue)=>
          onValue == PermissionStatus.notDetermined ? requestStoragePermission() 
          : onValue == PermissionStatus.denied ? false: true )
      : true
    );
```
then I made sure to check permission before calling the function, now i got simply this

> I/SimplePermission( 7572): Checking permission : android.permission.READ_EXTERNAL_STORAGE 

Got back manually disabled storage permission and then tried again, I got the prompt requesting permission, clicked `Allow` and something repeated. 

Could you please test it once again ?

**Comment by Sh1d0w** [comment]
@krngd2 The Android library I am using in my plugin, manages requests permissions on its own. Can you try to remove the SimplePermissions plugin and try directly invoking the image picker? 

In case you run it for first time it should prompt you for permissions via Android native ui.

If you deny them and click second time the plugin will throw exception with code `PERMISSION_DENIED` which you can catch in dart, thus you know user rejected the permissions. If They clicked `Don't show again` the exception code will be `PERMISSION_PERMANENTLY_DENIED`.

In such case you have to present them with dialog to tell them to manually enable those.

**Comment by krngd2** [comment]
Great, it is working after removing the SimplePermissions plugin but I need to have that plugin for the location permission. Any alternatives ?

**Comment by Sh1d0w** [comment]
I meant not to remove the plugin, but not to put the image picking function in a condition for permissions, as it handles it by itself.

**Comment by krngd2** [comment]
I havnt used it with image picker function!  Still it showed me this 

> I/SimplePermission(7572): Requesting permission status : 0

As i mentioned in above 

> Hey Thank you very much for the quick fix, I upgraded to version 2.3.29 and ran it, now it happens nothing when I click the button but I got
> 
> > I/SimplePermission(7572): Requesting permission status : 0
> 
> i have Simple Permissions plugin installed so i thought it might be permission issue, then i wrote a check permission function
> 
> ```
> Future<bool> requestStoragePermission(){ 
>   return SimplePermissions.checkPermission(Permission.ReadExternalStorage).then((onValue)=>
>     !onValue ? SimplePermissions.requestPermission(Permission.ReadExternalStorage).then((onValue)=>
>         onValue == PermissionStatus.notDetermined ? requestStoragePermission() 
>         : onValue == PermissionStatus.denied ? false: true )
>     : true
>   );
> ```
> then I made sure to check permission before calling the function, now i got simply this
> 
> > I/SimplePermission( 7572): Checking permission : android.permission.READ_EXTERNAL_STORAGE
> 
> Got back manually disabled storage permission and then tried again, I got the prompt requesting permission, clicked `Allow` and same thing repeated.
> 
> Could you please test it once again ?

**Comment by Sh1d0w** [comment]
I've added https://pub.dartlang.org/packages/simple_permissions to the example app in this repo and was able to run the image picker without problems.

Can you setup example repo where I can reproduce the issue, it may be something else in your code?
