### ISSUE TITLE
Android Crash 

### ISSUE THREAD

**Issue by tongyangsheng** [Sh1d0w/multi_image_picker#539]
when I run the example project, it works well.But when I use this plugin in my project, it crashed when open photos, this is log
```
D/CrashReport(24700): >>> com.tongyangsheng.flutterhealthy.MainActivity onPaused <<<
I/CrashReport-Native(24700): Set native info: isAppForeground(false)
W/ActivityThread(24700): handleWindowVisibility: no activity for token android.os.BinderProxy@cd527d1
V/ActivityThread(24700): callActivityOnCreate
D/CrashReport(24700): >>> com.sangcomz.fishbun.ui.album.AlbumActivity onCreated <<<
I/DecorView[](24700):  old windowMode:0 new windoMode:1
W/.flutterhealth(24700): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/.flutterhealth(24700): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/OverScrollerOptimization(24700): start init SmartSlideOverScroller and get the overscroller config
I/OverScrollerOptimization(24700): get the overscroller config
D/ActivityThread(24700): add activity client record, r= ActivityRecord{2df8ed token=android.os.BinderProxy@cd527d1 {com.tongyangsheng.flutterhealthy/com.sangcomz.fishbun.ui.album.AlbumActivity}} token= android.os.BinderProxy@cd527d1
D/CrashReport(24700): >>> com.sangcomz.fishbun.ui.album.AlbumActivity onResumed <<<
I/CrashReport-Native(24700): Set native info: isAppForeground(true)
D/DecorView(24700): showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
D/OpenGLRenderer(24700): disableOutlineDraw is true
D/HiTouch_PressGestureDetector(24700): onAttached, package=com.tongyangsheng.flutterhealthy, windowType=1, mHiTouchRestricted=false
D/mali_winsys(24700): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/RecyclerView(24700): No adapter attached; skipping layout
I/HwViewRootImpl(24700): removeInvalidNode all the node in jank list is out of time
D/DecorView(24700): showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager(24700): startInputReason = 1
D/AndroidRuntime(24700): Shutting down VM
I/QarthLog(24700): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(24700): [PatchStore] create disable file for com.tongyangsheng.flutterhealthy uid is 10257
E/AndroidRuntime(24700): FATAL EXCEPTION: main
E/AndroidRuntime(24700): Process: com.tongyangsheng.flutterhealthy, PID: 24700
E/AndroidRuntime(24700): java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/BaseRequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.tongyangsheng.flutterhealthy-L6JxojDM4byxSpf6Br3DxQ==/base.apk!classes2.dex)
E/AndroidRuntime(24700): 	at com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(GlideAdapter.kt:16)
E/AndroidRuntime(24700): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.kt:31)
E/AndroidRuntime(24700): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.kt:18)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
E/AndroidRuntime(24700): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
E/AndroidRuntime(24700): 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
E/AndroidRuntime(24700): 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
E/AndroidRuntime(24700): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
E/AndroidRuntime(24700): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/AndroidRuntime(24700): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(24700): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:978)
E/AndroidRuntime(24700): 	at android.view.View.layout(View.java:22147)
E/AndroidRuntime(24700): 	at android.view.ViewGroup.layout(ViewGroup.java:6493)
E/AndroidRuntime(24700): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3328)
E/AndroidRuntime(24700): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2819)
E/AndroidRuntime(24700): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
E/AndroidRuntime(24700): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
E/AndroidRuntime(24700): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
E/AndroidRuntime(24700): 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
E/AndroidRuntime(24700): 	at android.view.Choreographer.doFrame(Choreographer.java:776)
E/AndroidRuntime(24700): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
E/AndroidRuntime(24700): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(24700): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(24700): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(24700): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/AndroidRuntime(24700): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24700): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(24700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```
Any Help? thank you very much

**Comment by Sh1d0w** [comment]
As it doesn't happen with the example app please provide repo which I can checkout and reproduce.

**Comment by tongyangsheng** [comment]
Thank you very much, I think I have found the problem. As My project is maintained by multiple people, one of my partners use another plugin to pick image. I deleted all config about that plugin and the crash have gone.Thank you bro🤪
