### ISSUE TITLE
Crash while selecting more that max

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#54]
**Describe the bug**
Crashing application while trying to select more than maximum limit of images

**To Reproduce**
Set max to 10 for example. Select 10 images and tap on 11 image. It will crash
```
<!-- Insert example code here, that will help to reproduce the bug -->
```

**Expected behavior**
Actually it should not crash ) 

**Crash log**
```
D/AndroidRuntime(11890): Shutting down VM
E/AndroidRuntime(11890): FATAL EXCEPTION: main
E/AndroidRuntime(11890): Process: io.qwil.android, PID: 11890
E/AndroidRuntime(11890): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
E/AndroidRuntime(11890): 	at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
E/AndroidRuntime(11890): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
E/AndroidRuntime(11890): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
E/AndroidRuntime(11890): 	at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
E/AndroidRuntime(11890): 	at android.view.View.performClick(View.java:6891)
E/AndroidRuntime(11890): 	at android.view.View$PerformClick.run(View.java:26083)
E/AndroidRuntime(11890): 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime(11890): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(11890): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(11890): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(11890): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11890): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(11890): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(11890): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/io.qwil.android-G8QOX_Q3HD-7yzZ1UkXTNQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.qwil.android-G8QOX_Q3HD-7yzZ1UkXTNQ==/lib/arm64, /data/app/io.qwil.android-G8QOX_Q3HD-7yzZ1UkXTNQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime(11890): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
E/AndroidRuntime(11890): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(11890): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(11890): 	... 13 more
```

**Flutter (please complete the following information):**
- Version of `multi_image_picker`: 2.3.29

```
[✓] Flutter (Channel unknown, v1.1.1, on Mac OS X 10.14.2 18C54, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)
```

**Android (please complete the following information):**
 - Device: Samsung s8
 - OS: Oreo 8.1

**Additional context**

**Comment by Sh1d0w** [comment]
This is a known bug with the Android plugin I am using.

To fix it just add the translation strings as described in the docs:

https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization

**Comment by agnoam** [comment]
> This is a known bug with the Android plugin I am using.
> 
> To fix it just add the translation strings as described in the docs:
> 
> https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization

can you give me an example cause I didn't understand it.
