### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.clear()' on a null object reference

### ISSUE THREAD

**Issue by kw2019ltd** [Sh1d0w/multi_image_picker#566]
Bug Report

multi_image_picker version: 4.7.14

Is it happening on Android: Yes

Is it happening on iOS: not using it

 C:\Tools\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-IL)
    • Flutter version 1.22.0 at C:\Tools\flutter
    • Framework revision d408d302e2 (5 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\kotai\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

```

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.clear()' on a null object reference
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.onPostExecute(MultiImagePickerPlugin.java:246)
       at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetImageTask.onPostExecute(MultiImagePickerPlugin.java:198)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

![image](https://user-images.githubusercontent.com/47334522/95652874-f007a000-0afc-11eb-9215-f943954e9d12.png)

**Comment by kw2019ltd** [comment]
added PR
#591
