### ISSUE TITLE
pick image from camera

### ISSUE THREAD

**Issue by ninio0809** [Sh1d0w/multi_image_picker#598]
**Bug Report**

`multi_image_picker` version: ^4.7.14

Is it happening on Android: Yes 

Is it happening on iOS:  No 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [version 10.0.18363.1256], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!
```

if I use the camera to take picture it doesn't work in all files

and  give that error 
W/System.err(10443): java.io.IOException: Permission denied
W/System.err(10443):    at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err(10443):    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err(10443):    at java.io.File.createTempFile(File.java:2018)
W/System.err(10443):    at com.sangcomz.fishbun.util.CameraUtil.createImageFile(CameraUtil.java:64)
W/System.err(10443):    at com.sangcomz.fishbun.util.CameraUtil.takePicture(CameraUtil.java:31)
W/System.err(10443):    at com.sangcomz.fishbun.ui.picker.PickerController.takePicture(PickerController.java:41)
W/System.err(10443):    at com.sangcomz.fishbun.adapter.view.PickerGridAdapter$1.onClick(PickerGridAdapter.java:74)
W/System.err(10443):    at android.view.View.performClick(View.java:7140)
W/System.err(10443):    at android.view.View.performClickInternal(View.java:7117)
W/System.err(10443):    at android.view.View.access$3500(View.java:801)
W/System.err(10443):    at android.view.View$PerformClick.run(View.java:27355)
W/System.err(10443):    at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(10443):    at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(10443):    at android.os.Looper.loop(Looper.java:214)
W/System.err(10443):    at android.app.ActivityThread.main(ActivityThread.java:7397)
W/System.err(10443):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10443):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(10443):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
W/ConnectionTracker(10443): Exception thrown while unbinding
W/ConnectionTracker(10443): java.lang.IllegalArgumentException: Service not registered: ls@114816
W/ConnectionTracker(10443):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
W/ConnectionTracker(10443):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(10443):     at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):1)
W/ConnectionTracker(10443):     at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):2)
W/ConnectionTracker(10443):     at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):9)
W/ConnectionTracker(10443):     at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):3)
W/ConnectionTracker(10443):     at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):3)
W/ConnectionTracker(10443):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(10443):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(10443):     at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713082@20.47.13 (120406-0):5)
---------------------------------------------------------------------------------
note i have make camera permission in androidmanifest

**Comment by user97972** [comment]
Same issue for me. Were you able to solve it?

**Comment by oscarshaitan** [comment]
same issue here  https://github.com/Sh1d0w/multi_image_picker/issues/557 and the issue is now closed without solution

**Comment by CarlosCedeniio** [comment]
Try to add this
 <application
      android:requestLegacyExternalStorage="true" ...

**Comment by oscarshaitan** [comment]
> Try to add this
> <application
> android:requestLegacyExternalStorage="true" ...

I try this and still have this issue
