### ISSUE TITLE
E/MethodChannel#multi_image_picker( 7449): Failed to handle method call

### ISSUE THREAD

**Issue by kangshibiao123** [Sh1d0w/multi_image_picker#602]
E/om.medicine.ap( 7449): Invalid ID 0x00000000.
E/MethodChannel#multi_image_picker( 7449): Failed to handle method call
E/MethodChannel#multi_image_picker( 7449): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/MethodChannel#multi_image_picker( 7449): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
E/MethodChannel#multi_image_picker( 7449): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
E/MethodChannel#multi_image_picker( 7449): 	at android.content.res.Resources.getDrawable(Resources.java:845)
E/MethodChannel#multi_image_picker( 7449): 	at android.content.Context.getDrawable(Context.java:654)
E/MethodChannel#multi_image_picker( 7449): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
E/MethodChannel#multi_image_picker( 7449): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:556)
E/MethodChannel#multi_image_picker( 7449): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:263)
E/MethodChannel#multi_image_picker( 7449): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#multi_image_picker( 7449): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#multi_image_picker( 7449): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#multi_image_picker( 7449): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#multi_image_picker( 7449): 	at android.os.MessageQueue.next(MessageQueue.java:327)
E/MethodChannel#multi_image_picker( 7449): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#multi_image_picker( 7449): 	at android.app.ActivityThread.main(ActivityThread.java:7046)
E/MethodChannel#multi_image_picker( 7449): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#multi_image_picker( 7449): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
E/MethodChannel#multi_image_picker( 7449): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
I/flutter ( 7449): PlatformException(error, Resource ID #0x0, null, android.content.res.Resources$NotFoundException: Resource ID #0x0
I/flutter ( 7449): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
I/flutter ( 7449): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
I/flutter ( 7449): 	at android.content.res.Resources.getDrawable(Resources.java:845)
I/flutter ( 7449): 	at android.content.Context.getDrawable(Context.java:654)
I/flutter ( 7449): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
I/flutter ( 7449): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:556)
I/flutter ( 7449): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:263)
I/flutter ( 7449): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter ( 7449): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter ( 7449): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter ( 7449): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 7449): 	at

**Comment by oswaldocueto01** [comment]
The same issue
