### ISSUE TITLE
plugin crashes when you try take picture using the camera on Android

### ISSUE THREAD

**Issue by rognikiv** [Sh1d0w/multi_image_picker#66]
**Describe the bug**
When you set enableCamera to true and try tap the "camera" button, the plugin will crash. I'm using the sample code provided on your website.

**To Reproduce**

```
Future<void> loadAssets() async {
    setState(() {
      images = List<Asset>();
    });

    List<Asset> resultList;
    String error;

    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
        enableCamera: true
      );
    } on PlatformException catch (e) {
      error = e.message;
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      if (resultList != null) images = resultList;
      if (error == null) _error = 'No Error Dectected';
    });
  }
```
**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: 2.3.29

**Output before crash**

```Launching lib/main.dart on SM G920W8 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM G920W8...
D/ViewRootImpl(13944): ViewPostImeInputStage ACTION_DOWN
I/Timeline(13944): Timeline: Activity_launch_request id:io.afriksell.fluttertester time:179253303
W/art     (13944): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/PhoneWindow(13944): *FMB* installDecor mIsFloating : false
D/PhoneWindow(13944): *FMB* installDecor flags : -2139029248
I/ListPopupWindow(13944): Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
D/Activity(13944): performCreate Call Injection manager
I/InjectionManager(13944): dispatchOnViewCreated > Target : com.zhihu.matisse.ui.MatisseActivity isFragment :false
D/PhoneWindow(13944): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
D/PhoneWindow(13944): *FMB* isFloatingMenuEnabled return false
D/mali_winsys(13944): new_window_surface returns 0x3000,  [1440x2560]-format:1
I/InjectionManager(13944): dispatchCreateOptionsMenu :com.zhihu.matisse.ui.MatisseActivity
I/InjectionManager(13944): dispatchPrepareOptionsMenu :com.zhihu.matisse.ui.MatisseActivity
I/Timeline(13944): Timeline: Activity_idle id: android.os.BinderProxy@3627f0a4 time:179253613
V/ActivityThread(13944): updateVisibility : ActivityRecord{3727dde1 token=android.os.BinderProxy@f0d140a {io.afriksell.fluttertester/io.afriksell.fluttertester.MainActivity}} show : false
```

**Output after crash**

```Launching lib/main.dart on SM G920W8 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM G920W8...
D/ViewRootImpl(13944): ViewPostImeInputStage ACTION_DOWN
I/Timeline(13944): Timeline: Activity_launch_request id:io.afriksell.fluttertester time:179253303
W/art     (13944): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/PhoneWindow(13944): *FMB* installDecor mIsFloating : false
D/PhoneWindow(13944): *FMB* installDecor flags : -2139029248
I/ListPopupWindow(13944): Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
D/Activity(13944): performCreate Call Injection manager
I/InjectionManager(13944): dispatchOnViewCreated > Target : com.zhihu.matisse.ui.MatisseActivity isFragment :false
D/PhoneWindow(13944): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
D/PhoneWindow(13944): *FMB* isFloatingMenuEnabled return false
D/mali_winsys(13944): new_window_surface returns 0x3000,  [1440x2560]-format:1
I/InjectionManager(13944): dispatchCreateOptionsMenu :com.zhihu.matisse.ui.MatisseActivity
I/InjectionManager(13944): dispatchPrepareOptionsMenu :com.zhihu.matisse.ui.MatisseActivity
I/Timeline(13944): Timeline: Activity_idle id: android.os.BinderProxy@3627f0a4 time:179253613
V/ActivityThread(13944): updateVisibility : ActivityRecord{3727dde1 token=android.os.BinderProxy@f0d140a {io.afriksell.fluttertester/io.afriksell.fluttertester.MainActivity}} show : false

D/ViewRootImpl(13944): ViewPostImeInputStage ACTION_DOWN
D/AndroidRuntime(13944): Shutting down VM
E/AndroidRuntime(13944): FATAL EXCEPTION: main
E/AndroidRuntime(13944): Process: io.afriksell.fluttertester, PID: 13944
E/AndroidRuntime(13944): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/AndroidRuntime(13944): 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
E/AndroidRuntime(13944): 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
E/AndroidRuntime(13944): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
E/AndroidRuntime(13944): 	at com.zhihu.matisse.internal.utils.MediaStoreCompat.dispatchCaptureIntent(MediaStoreCompat.java:86)
E/AndroidRuntime(13944): 	at com.zhihu.matisse.ui.MatisseActivity.capture(MatisseActivity.java:424)
E/AndroidRuntime(13944): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter$1.onClick(AlbumMediaAdapter.java:75)
E/AndroidRuntime(13944): 	at android.view.View.performClick(View.java:5217)
E/AndroidRuntime(13944): 	at android.view.View$PerformClick.run(View.java:20983)
E/AndroidRuntime(13944): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(13944): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(13944): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(13944): 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/AndroidRuntime(13944): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13944): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13944): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(13944): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Flutter doctor**

 
```[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-CA)
    • Flutter version 1.0.0 
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Ives/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM G920W8 • 02157df29507453b • android-arm64 • Android 5.0.2 (API 21)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**iOS (please complete the following information):**
 - Swift Version: [e.g. 4.0]

**Android (please complete the following information):**
 - Device: SM G920W8
 - OS: 5.0.2

**Additional context**

**Comment by Sh1d0w** [comment]
Hi.

Did you follow the steps to enable the camera on Android as described in the docs https://sh1d0w.github.io/multi_image_picker/#/enablecamera?id=enable-camera-on-android ?

**Comment by rognikiv** [comment]
Thank you! 
I followed the steps but I forgot to change
android:authorities="YOUR_PACKAGE_NAME_HERE.multiimagepicker.fileprovider"
to include my package name. 
You've done a great job with the plugin 👍 

Is there a way to customize the strings for iOS?
https://sh1d0w.github.io/multi_image_picker/#/theming

I would like to include French support on the application.

Thank you!

**Comment by Sh1d0w** [comment]
@rognikiv The plugin I am using for iOS uses System localizations and will automatically detect the device language and appropriately switch translations.

At this point there is not override functionality on iOS.

**Comment by rognikiv** [comment]
@Sh1d0w Perfect! Thank you :D
