### ISSUE TITLE
exif 

### ISSUE THREAD

**Issue by kimhan** [Sh1d0w/multi_image_picker#67]
Most image cannot get metadata

[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
[2015, 1511, 2217, 1330]
^
#0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:131:5)
#1      int._parseRadix (dart:core/runtime/libintegers_patch.dart:157:16)
#2      int._parse (dart:core/runtime/libintegers_patch.dart:100:12)
#3      int.parse (dart:core/runtime/libintegers_patch.dart:63:12)
#4      _castAsInt (package:multi_image_picker/metadata.dart:950:37)
#5      new ExifMetadata.fromMap (package:multi_image_picker/metadata.dart:623:23)
#6      new Metadata.fromMap (package:multi_image_picker/metadata.dart:12:29)
#7      MultiImagePicker.requestMetadata (package:multi_image_picker/picker.dart:131:21)
<asynchronous suspension>

**Comment by Sh1d0w** [comment]
Never mind, I was able to reproduce the error, fix is coming in the next few minutes, thanks for the report.

**Comment by Sh1d0w** [comment]
This now is fixed in version 2.3.33
