### ISSUE TITLE
App Getting crashed while opening camera

### ISSUE THREAD

**Issue by krsolutions** [Sh1d0w/multi_image_picker#84]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.zhihu.matisse.internal.utils.MediaStoreCompat.dispatchCaptureIntent(MediaStoreCompat.java:86)
        at com.zhihu.matisse.ui.MatisseActivity.capture(MatisseActivity.java:424)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter$1.onClick(AlbumMediaAdapter.java:75)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6696)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2019-03-12 05:02:33.292 589-1892/? E/SurfaceFlinger: Failed to find layer (in.krsolutions.leader/com.zhihu.matisse.ui.MatisseActivity#0) in layer parent (no-parent).
2019-03-12 05:02:33.297 1478-3055/? E/ActivityTrigger: activityResumeTrigger: not whiteListedin.krsolutions.leader/in.krsolutions.leader.MainActivity/1
2019-03-12 05:02:34.974 1478-1576/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2019-03-12 05:02:34.974 1478-1576/? E/ANDR-PERF-JNI: gIOPHAl initialized
2019-03-12 05:02:34.976 1478-1576/? E/ANDR-PERF-JNI: gIOPHAl calling iopstart from default
2019-03-12 05:02:34.977 568-568/? E/ANDR-IOP: IOP HAL: Received pkg_name = in.krsolutions.leader pid = 3244
2019-03-12 05:02:34.977 568-568/? E/ANDR-IOP: event data pool ran empty
2019-03-12 05:02:41.064 2580-2619/? E/octvm_klo: Not get wanted event from the watchset in 8000ms for 2

**Comment by Sh1d0w** [comment]
You haven't added a file provider. Please follow the documentation here https://sh1d0w.github.io/multi_image_picker/#/enablecamera?id=enable-camera-on-android

**Comment by krsolutions** [comment]
Below snippet is already there in my code.


<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="multiimagepicker_files"
        path="Pictures"/>
</paths>







        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />

        <provider
            android:name="com.vitanov.multiimagepicker.MultiImagePickerFileProvider"
            android:authorities="YOUR_PACKAGE_NAME_HERE.multiimagepicker.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public"></meta-data>
        </provider>
    </application>
</manifest>

**Comment by Sh1d0w** [comment]
You need to replace `YOUR_PACKAGE_NAME_HERE` with your package name ....

**Comment by krsolutions** [comment]
**Getting another issue while exporting signed apk**

Could not find com.github.Sh1d0w:Matisse:040393d.
Searched in the following locations:
  - file:/Users/reddy/Library/Android/sdk/extras/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - file:/Users/reddy/Library/Android/sdk/extras/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - file:/Users/reddy/Library/Android/sdk/extras/google/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - file:/Users/reddy/Library/Android/sdk/extras/google/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - file:/Users/reddy/Library/Android/sdk/extras/android/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - file:/Users/reddy/Library/Android/sdk/extras/android/m2repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - file:/Users/reddy/.m2/repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - file:/Users/reddy/.m2/repository/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - https://repo.maven.apache.org/maven2/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - https://repo.maven.apache.org/maven2/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - https://maven.google.com/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - https://maven.google.com/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - http://dl.bintray.com/jlmd/maven/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - http://dl.bintray.com/jlmd/maven/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
  - https://jcenter.bintray.com/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.pom
  - https://jcenter.bintray.com/com/github/Sh1d0w/Matisse/040393d/Matisse-040393d.jar
Required by:
    project :app > project :multi_image_picker

**Comment by Sh1d0w** [comment]
This should be fixed in version 3.0.23.
