### ISSUE TITLE
Couldn't launch app in android 7 api 24

### ISSUE THREAD

**Issue by hgl** [Sh1d0w/multi_image_picker#98]
**Bug Report**

`multi_image_picker` version: 4.0.0

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.13.6 17G5019, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)
```

**Describe the bug**

I created a new flutter app, using swift and kotlin, added `multi_image_picker: ^4.0.0` to `dependencies`, copied `main.dart` and `asset_view.dart` from repo's example to my `lib` added the `uses-permission` entries to AndroidManifest.xml.

And running the flutter failed on launch, saying the app stopped, console displayed the following error.

Any idea how to solve it?

```
2019-03-27 19:17:53.486 7231-7231/com.example.image_picker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.image_picker, PID: 7231
    java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.example.image_picker-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.image_picker-2/lib/x86_64, /data/app/com.example.image_picker-2/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5814)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.example.image_picker-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.image_picker-2/lib/x86_64, /data/app/com.example.image_picker-2/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5799)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by Sh1d0w** [comment]
Strange it is searching for `android.support.v4.content.FileProvider` which was deprecated in AndroidX and version 4 of this plugin.

Can you check if your AndroidManifest contains reference to it? Also you can try to run the example app in this project.

**Comment by hgl** [comment]
This is my AndroidManifest.

And strangely, I can run the example without issues.

I wonder if it's because I pulled the packages from the internet and example uses local package?

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.image_picker">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="image_picker"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by Sh1d0w** [comment]
@hgl What is in the pub registry is in sync with this repository.

Do you have any other plugins added to your project, that may cause conflict?

**Comment by hgl** [comment]
Nope, this is a newly created app, with no dependencies other than `multi_image_picker`.

I'm still pretty new to flutter, by "pub registry" do you mean the flutter package files downloaded locally? I wonder where are they so I could check? I expect it to download to a path akin to node_modules, but can't find it anywhere.

```yaml
name: image_picker
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  multi_image_picker: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

**Comment by Sh1d0w** [comment]
@hgl I was able to reproduce the issue. Will let you know when I have a solution. Thanks for the report.

**Comment by Sh1d0w** [comment]
@hgl I've found the problem. Basically when you create a project, flutter still creates it with the old android support libraries. In order to use the multi_image_picker you need your project to be migrated to AndroidX as stated in the docs. I guess flutter will need to update their android template soon, as most of their plugins also are migrated to AndroidX.

To fix it for you, just follow this guide https://developer.android.com/jetpack/androidx/migrate

I am going to close this as it is not problem of this library, rather than Android thing.

**Comment by hgl** [comment]
Thanks. After migrating to AndroidX, I can start the app. Although when the app starts or the image picking screen closes, a white screen stay for a long time, (example also behave like this).

Not sure if it's AndroidX related.

**Comment by Sh1d0w** [comment]
@hgl What device are you running it on? I can not reproduce it in the emulator:

![Kapture 2019-03-27 at 15 46 39](https://user-images.githubusercontent.com/5074917/55080965-afc20780-50a7-11e9-9bbf-1fa5d34cd8dd.gif)

**Comment by hgl** [comment]
After upgrading flutter SDK, it's fine now. Thanks for the hand-holding.

**Comment by lp007lp** [comment]
@hgl hello,how did my flutter project which used the multi_image_picker run successfully in vs code after migrating to the AndroidX?

**Comment by hgl** [comment]
You mean it doesn’t run? What’s the error message? I didn’t encounter any issues after migrating.
